- backend/build.gradle
- backend/src/main/java/kernel360/techpick/config/JpaAuditingConfig.java
- backend/src/main/java/kernel360/techpick/config/JpaAuditingConfiig.java
- backend/src/main/java/kernel360/techpick/config/P6SpySqlLoggerConfig.java
- backend/src/main/java/kernel360/techpick/entity/admin/Administrator.java
- backend/src/main/java/kernel360/techpick/entity/admin/CrawlingTopicMapping.java
- backend/src/main/java/kernel360/techpick/entity/admin/Topic.java
- backend/src/main/java/kernel360/techpick/entity/article/Article.java
- backend/src/main/java/kernel360/techpick/entity/article/ArticleDetail.java
- backend/src/main/java/kernel360/techpick/entity/article/ArticleTopic.java
- backend/src/main/java/kernel360/techpick/entity/article/RawCrawledArticle.java
- backend/src/main/java/kernel360/techpick/entity/blog/Blog.java
- backend/src/main/java/kernel360/techpick/entity/common/CreatedAndUpdatedTimeColumn.java
- backend/src/main/java/kernel360/techpick/entity/event/AricleViewEvent.java
- backend/src/main/java/kernel360/techpick/entity/event/EventLocation.java
- backend/src/main/java/kernel360/techpick/entity/subscriber/EmailSubscriber.java
- backend/src/main/java/kernel360/techpick/entity/user/AgeGroup.java
- backend/src/main/java/kernel360/techpick/entity/user/JobGroup.java
- backend/src/main/java/kernel360/techpick/entity/user/User.java
- backend/src/main/java/kernel360/techpick/entity/user/UserTopic.java
- backend/src/main/resources/application.yaml
- backend/src/main/resources/logback-spring.xml
- Close #14 
- 기능 : ERD 기반 Entity 정의
- issue : #14 
- ERD 기반 엔티티 13개 추가
- [`crawling_topic_mapping`](https://github.com/Kernel360/F2-TECHPICK/blob/back/feat/%2314/backend/src/main/java/kernel360/techpick/entity/admin/CrawlingTopicMapping.java): 블로그 태그 - 토픽 매핑 설정 테이블 :warning: 주석 확인해주세요.
- [`raw_crawled_article`](https://github.com/Kernel360/F2-TECHPICK/blob/back/feat/%2314/backend/src/main/java/kernel360/techpick/entity/article/RawCrawledArticle.java) : 크롤링데이터를 밀어넣는 Raw 테이블. :warning: 칼럼 타입은 변경 예정입니다.
- 참고
[ER 다이어그램 링크](https://www.drawdb.app/editor?shareId=f1baf5f261e24916090637074dd899b0)
- SQL 로깅 + logback 설정
- logback : File Appender가 `/data` 경로에 로그 파일을 생성함.
- p6spy : SQL 개행 및 값 표시
- 테이블 제약조건 중 `not null`을 최대한 설정했음. 
- 추후 불필요한 제약조건은 빼거나 추가 예정.
> feat: ERD 기반 Entity 정의

- backend/build.gradle
- backend/src/main/java/kernel360/techpick/config/RestTemplateConfig.java
- backend/src/main/java/kernel360/techpick/entity/article/Article.java
- backend/src/main/java/kernel360/techpick/entity/article/RawCrawledArticle.java
- backend/src/main/java/kernel360/techpick/rss/controller/RssController.java
- backend/src/main/java/kernel360/techpick/rss/dto/RssResponse.java
- backend/src/main/java/kernel360/techpick/rss/dto/Url.java
- backend/src/main/java/kernel360/techpick/rss/repository/RssRepository.java
- backend/src/main/java/kernel360/techpick/rss/service/RssService.java
- Close #16 
- 기능 : 기술 블로그들의 RSS feed를 참고하여 데이터 수집
- issue : #16 
- xml 데이터를 읽어오기 위한 어노테이션, 설정 추가
- `backend/build.gradle`,  `RssResponse`, `RestTemplateConfig` 참조
- Rss 데이터 수집 기능 구현
- `RssController`, `postman`을 이용하여 rss 데이터를 가지고 올 수 있습니다.
- `RssService`의 `getNewRss` 메서드를 이용하여 매일 새벽 3시에 스케줄러를 통해 새로운 글을 탐지합니다.
또한, 초기에 아무런 데이터가 없을 경우 모든 데이터를 가져옵니다.
- `RssRepository`에서 크롤링된 게시글들의 링크만 가져옵니다.
- `Url` enum의 경우 Blog entity의 rssUrl로 변경 예정
- DB에서 모든 블로그들의 링크를 가져오는 부분 -> 각 블로그 별 링크를 가져와서 새 글 탐지하는 방식으로 변경 예정
> feat: RSS 기능 구현

- backend/build.gradle
- backend/src/test/java/kernel360/techpick/fixture/JobGroupFixture.java
- backend/src/test/java/kernel360/techpick/fixture/LinkFixture.java
- backend/src/test/java/kernel360/techpick/fixture/TagFixture.java
- backend/src/test/java/kernel360/techpick/fixture/UserFixture.java
- backend/src/test/resources/application-test.yaml
- Close #83
- 기능 : 테스트에서 사용할 객체(엔티티/dto 등)를 제공하는 클래스
- issue : #83
정적 팩토리 메소드를 사용하는 경우 테스트용 임시 객체를 생성하기 어려움
그렇다고 `@Setter` `@AllArgsConstructor` `@Builder`를 사용해 정적 팩토리 메소드의 이점을 잃어버리기엔 매우 아쉽다고 생각
테스트용 클래스를 정의하고 ObjectMapper를 활용해 테스트에 필요한 객체를 제한적으로 생성할 수 있음
값을 설정해야한는 경우 정적 메소드를 오버로딩하여 설정 가능
[참고 1기 Orury](https://github.com/Kernel360/f1-Orury-Backend/tree/develop/orury-domain/src/testFixtures/java/org/orury/domain)
테스트 코드를 작성하며, 다른 객체생성자가 필요한 경우 _**주석 아래쪽에 정적 메소드를 추가**_ 하여 사용
> [test] 테스트 Fixture 구현

- backend/data/develop/mysql-files/data.sql
- backend/data/develop/mysql-files/rss_blog.csv
- backend/project-setup/rss_setting.md
- backend/src/main/java/kernel360/techpick/core/model/rss/RssSupportingBlog.java
- backend/src/main/resources/data.sql
- Close #95 
- 기능 : mysql에서 rss blog url sql + csv 파일 import
- issue : #95 
docker mysql에 접속해서 sql 파일 import 하는 방법 정의
data.sql 파일 안에 csv 파일 load 하는 명령어 정의 되어 있음.
data.sql 파일 import 시 rss csv 파일 로드됨.
`rss_blog.csv` 중복된 url 제거
`RssSupportingBlog` rssFeedUrl unique index 추가
- 배포 서버에 1번만 csv 파일 load
- 관리자가 크롤링할 링크 추가
> feat: mysql에서 rss blog url sql 파일 import

- backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderMapper.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderProvider.java
- backend/src/main/java/kernel360/techpick/feature/folder/repository/FolderRepository.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderCreateRequest.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderResponse.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderUpdateRequest.java
- Close #115
- 기능 : Folder 서비스 CRUD와 검증로직 구현
- issue : #115
- `createFolder(Long userId, FolderCreateRequest request)`
- `List<FolderResponse> getFolderListByUserId(Long userId)`
- `List<FolderResponse> getFolderListByParentId(Long userId, Long parentId)`
- 특정 폴더를 부모로 가지는 폴더 리스트 반환(즉, 특정 폴더의 자식 폴더 리스트 반환)
- 폴더 세부내용 보기와 폴더구조json 검증에서 사용할 예정
- `void updateFolder(Long userId, FolderUpdateRequest request)`
- `void moveToUnclassified(Long userId, Long folderId)`
- 특정 폴더를 미분류 폴더로 이동 
- `void moveToRecycleBin(Long userId, Long folderId)`
- 특정 폴더를 휴지통으로 이동
- `void deleteFolder(Long userId, Long folderId)`
- 특정 폴더를 삭제 후 해당 폴더의 자식들을 미분류폴더로 이동
- `validateFolderAccess(Long userId, Folder folder)` : 특정 폴더가 본인 폴더인지 검증하는 로직
- `validateDuplicateFolderName(Long userId, String name)` : 폴더이름이 중복되는지 검증하는 로직 …
> [feat] Folder Service 구현

- backend/src/main/java/kernel360/techpick/core/model/link/Link.java
- backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
- backend/src/main/java/kernel360/techpick/feature/link/model/LinkMapper.java
- backend/src/main/java/kernel360/techpick/feature/link/service/dto/LinkRequest.java
- backend/src/main/java/kernel360/techpick/feature/link/service/dto/LinkResponse.java
- backend/src/main/java/kernel360/techpick/feature/pick/exception/ApiPickErrorCode.java
- backend/src/main/java/kernel360/techpick/feature/pick/exception/ApiPickException.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickCreateRequest.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickResponse.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickTagResponse.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickTagUpdateRequest.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickUpdateRequest.java
- backend/src/test/java/kernel360/techpick/fixture/LinkFixture.java
- backend/src/test/java/kernel360/techpick/fixture/TagFixture.java
- Close #45 
- 기능 : Pick DTO 설계
- issue : #45 
- Pick Entity에 Folder 연관 관계 설정
- Pick Error Code, Exception 구현
- Link Entity에 imageUrl 추가
-  필드 추가에 따라 `linkMapper`, `linkFixture`, `linkRequest`, `linkResponse` 수정
-  생성 메서드에서 `null` 넣은 것은 rss link를 직접 관리자가 넣어줄 경우에 og:image를 가져올 수 없기 때문
- Pick, PickTag dto 설계 및 구현
dto 구현은 했으나, 추후 수정될 가능성 있음.
프론트 쪽과 얘기한 이후에 정확하게 정의할 예정.
`PickTagUpdateRequest`에 Pick에 포함되어 있는 Tag들은 요청을 리스트로 받게 될 것인지? 하나씩 받게 될 것인지?
> feat: Pick DTO 설계

- backend/src/main/java/kernel360/techpick/core/auth/service/CustomOAuth2Service.java
- backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
- backend/src/main/java/kernel360/techpick/core/model/folder/FolderType.java
- backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
- backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderException.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderMapper.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderProvider.java
- backend/src/main/java/kernel360/techpick/feature/folder/repository/FolderRepository.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderCreateRequest.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderResponse.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderUpdateRequest.java
- Close #122
- 기능 : 기본폴더 CRUD 관련 리팩토링
- issue : #122
1. `Folder` 엔티티의 부모폴더를 나타내는 필드명이 `parentFolder`로 변경
관련 메소드 및 필드명에도 `parentFolder`로 변경
2. `FolderType`으로 조회하지 않고, 미분류폴더와 휴지통을 조회하는 메소드를 분리
3. 기본 폴더(미분류폴더, 휴지통)는 수정/삭제 불가능하도록 검증 로직 추가
4. 회원가입시 기본폴더 추가되도록 기능 구현
- 미분류 폴더 `FolderType.UNCLASSIFIED`
- 휴지통 `FolderType.RECYCLE_BIN`
1. 부모 폴더라는것을 더욱 명확하게 나타내기 위함
2. 기본폴더 조회 시 메소드를 분리하여 명확하게 처리
- `FolderType`을 파라미터로 받을 경우 NPE 발생 가능성 있음
- `FolderType.GENERAL`의 경우 결과값이 복수일 수 있음
3. 기본 폴더(미분류폴더, 휴지통)는 수정/삭제/이동이 불가능하도록 검증 로직 추가
- 기본 폴더의 경우 삭제/수정/이동이 불가능 해야함
4. 회원가입시 기본폴더가 추가되도록 기능 구현
- 회원가입시 기본폴더가 자동으로 생성되도록 해서, 회원이라면 기본폴더가 항상 존재함을 보장
비즈니스 로직에 심각한 영향을 끼치는 경우가 아니라면 이미 설계된 entity를 수정하는것은 좋지 않다고 생각함
> [REFACTOR] 기본 폴더 CRUD 관련 리팩토링

- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
- Close #131
- 기능 : 불필요한 어노테이션 제거
- issue : #131
`private void validateFolderAccess(Long userId, @NotNull Folder folder)`
->`private void validateFolderAccess(Long userId, Folder folder)`
내부 로직에서 null 체크를 진행하므로 `@NotNull` 어노테이션 불필요
> [FIX] 불필요한 어노테이션 제거

- backend/src/main/java/kernel360/techpick/core/auth/service/CustomOAuth2Service.java
- backend/src/main/java/kernel360/techpick/core/model/folder/FolderType.java
- Close #139
- 기능 : 기본 폴더로 root 폴더 추가
- issue : #139
- 기본 폴더로 root 폴더 추가
- `FolderType.ROOT` 추가
- `BasicFolder EnumSet`에 `ROOT` 추가
- 회원가입시 root 폴더도 자동으로 생성
기본폴더에 대한 내용이 바뀌는것이므로, merge된 이후에 pull 한번씩 해주세요
> [FEAT] 기본 폴더로 root 폴더 추가

- backend/src/main/java/kernel360/techpick/core/auth/Filter/TokenAuthenticationFilter.java
- backend/src/main/java/kernel360/techpick/core/util/CookieUtil.java
- Close #153
- 기능 : 로그인 확인용 쿠키 구현
- issue : #153
- 로그인시 로그인 확인용 쿠키: `techPickLogin` 생성
- 유효기간은 `access_token`과 동일
- httpOnly 옵션 false
- 인증 실패시(jwt 없을시) `techPickLogin` 삭제
> [FEAT] 로그인 확인용 쿠키 구현

- backend/src/main/java/kernel360/techpick/feature/folder/controller/FolderApi.java
- backend/src/main/java/kernel360/techpick/feature/folder/controller/FolderController.java
- backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderMapper.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderStructureService.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderCreateDto.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderDeleteDto.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderIdDto.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderMoveDto.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/dto/FolderUpdateRequest.java
- backend/src/main/java/kernel360/techpick/feature/folder/validator/FolderValidator.java
- Close #160
- 기능
- Folder Api 구현
- FolderService, FolderStructureService 분리
- issue : #160
- Folder Api 구현
- FolderApi
- FolderController
- FolderService 분리
- FolderController에서 사용하는 메소드를 FolderService로 분리
- StructureService에서 사용하는 메소드들을 FolderStructureService로 분리
- FolderStructureService의 경우 Folder 엔티티를 직접 반환(dto로 변환 안함)
- FolderDto 세분화
- 메소드 파라미터가 많아져 혼란이 생길 가능성이 있어 dto로 래핑
> [FEAT] Folder Api 구현 및 FolderService 리팩토링

- backend/src/main/java/kernel360/techpick/core/auth/handler/OAuth2SuccessHandler.java
- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
- backend/src/main/java/kernel360/techpick/core/model/folder/FolderType.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickApi.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickController.java
- backend/src/main/java/kernel360/techpick/feature/pick/model/PickProvider.java
- backend/src/main/java/kernel360/techpick/feature/pick/repository/PickRepository.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- Close #204 
- 기능 : 픽 중복 조회 기능, 로그아웃 API, CORS 설정 추가
- issue : #204 
- 픽 중복 조회 기능 구현
- 로그아웃 API 기능 구현
- 스프링 시큐리티 필터에 `/api/logout` 설정, JSESSIONID, access_token 제거
- CORS에 익스텐션 배포용 아이디 추가
- `OAuth2SuccessHandler`에 access_token 상수로 선언된 부분 `SecurityConfig`로 이동
`postman`으로 `/api/logout` `post` 요청 보냈을 때 쿠키 삭제되는 것 확인 완료
logout 할 때 `GET` 요청으로도 로그아웃이 가능한 문제 발생.
`CSRF` 설정 활성화하여 `POST` 요청 시에만 로그아웃이 가능하도록 변경
> [FEAT] 픽 중복 조회 기능, 로그아웃 API, CORS 설정 추가

- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickApi.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickController.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- Close #221 
- 기능 : url로 Pick 조회 시 리턴 타입 변경
- issue : #221 
url로 Pick 조회 시 리턴 타입 (`Long` -> `PickResponse`)로 변경
프론트에서 Long 타입 반환해주면, 반환된 아이디 값을 가지고 다시 요청을 보내서 가져와야 함.
이 방식을 사용하면, 요청을 2번 보내야 하여 렌더링 시간이 느려지게 됨.
픽 생성 전에 Url로 픽 정보를 조회하여 있으면 수정, 없으면 생성하는데 이 과정에서 리턴 데이터를 활용하려고 함.
리턴된 데이터를 활용하면 렌더링 시간이 빨라지게 됨.
> [REFACTOR] url로 Pick 조회 시 리턴 타입 변경

- frontend/techpick-extension/src/widgets/TagPicker/TagAutocompleteDialog/index.tsx
- Close #253 
- 기능 :
- issue : #253 
이제 태그 생성시 연속적으로 입력해서 생성하지 못합니다.
> [FIX] 익스텐션 태그 중복 생성 차단

- backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
- backend/src/main/java/kernel360/techpick/feature/domain/pick/service/PickServiceImpl.java
- 기능 : 프론트가 전송한 리스트로 픽 태그 관계를 업데이트하는 로직이 빠져서 추가함.
- issue : #295
> [FIX] 픽-태그 관계 테이블 업데이트 로직 추가

- backend/src/main/java/kernel360/techpick/core/model/folder/FolderRepository.java
- backend/src/main/java/kernel360/techpick/feature/api/folder/dto/FolderApiMapper.java
- backend/src/main/java/kernel360/techpick/feature/api/folder/dto/FolderApiRequest.java
- backend/src/main/java/kernel360/techpick/feature/application/FolderFacade.java
- backend/src/main/java/kernel360/techpick/feature/application/TagFacade.java
- backend/src/main/java/kernel360/techpick/feature/domain/folder/dto/FolderCommand.java
- backend/src/main/java/kernel360/techpick/feature/domain/folder/exception/ApiFolderErrorCode.java
- backend/src/main/java/kernel360/techpick/feature/domain/folder/exception/ApiFolderException.java
- backend/src/main/java/kernel360/techpick/feature/domain/folder/service/FolderService.java
- backend/src/main/java/kernel360/techpick/feature/domain/folder/service/FolderServiceImpl.java
- backend/src/main/java/kernel360/techpick/feature/domain/pick/service/PickServiceImpl.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/FolderAdapter.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/FolderAdapterImpl.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/FolderAdaptor.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/FolderAdaptorImpl.java
- Close #315
- 기능 : Folder 도메인 리팩토링
- issue : #315
- FolderFacade 제거
- FolderService가 Folder에 대한 모든 비즈니스 로직을 가지도록 리팩토링
- 사용자 검증과 같은 비즈니스 로직적인 검증도 Service에서 처리하도록 함
- FolderAdaptor는 엔티티 변경을 db에 반영하는 책임만 가지도록 리팩토링
- 기본폴더 조회 메소드 추가
- `FolderResult getRootFolder(Long userId)`
- `FolderResult getRecycleBin(Long userId)`
- `FolderResult getUnclassifiedFolder(Long userId)`
- idList로 조회 시 순서 보장하는 조회와 보장하지 않는 조회 메소드 분리
- `List<Folder> getFolderList(List<Long> idList)`
- `List<Folder> getFolderListPreservingOrder(List<Long> idList)`
@sangwonsheep 
Pick 구현 시에도 idList를 받아서 idList 순서를 유지한 PickList를 반환하는 메소드가 필요할것으로 예상됨
> [REFACTOR] Folder 도메인 리팩토링

- backend/src/main/java/kernel360/techpick/feature/api/tag/controller/TagApiController.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiMapper.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiRequest.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiResponse.java
- backend/src/main/resources/application.yaml
- Close #324
- 기능 : Tag API 구현 및 Swagger 명세
- issue : #324
- `ResponseEntity<List<TagApiResponse.Read>> getAllUserTag(Long userId)`
- `ResponseEntity<TagApiResponse.Create> createTag(Long userId, TagApiRequest.Create request)`
- `ResponseEntity<Void> updateTag(Long userId, TagApiRequest.Update request)`
- `ResponseEntity<Void> moveTag(Long userId, TagApiRequest.Move request)`
- `ResponseEntity<Void> deleteTag(Long userId, TagApiRequest.Delete request)`
- API 설명
- 요청 예시
- 응답 형식 및 response code
> [FEAT] Tag API 구현 및 Swagger 명세

- backend/src/main/java/kernel360/techpick/core/annotation/LoginUserId.java
- backend/src/main/java/kernel360/techpick/core/config/WebConfig.java
- backend/src/main/java/kernel360/techpick/core/util/LoginUserArgumentResolver.java
- Close #325
- 기능 : LoginUserId 커스텀 어노테이션 구현
- issue : #325
V1의 컨트롤러에서 Authentication을 주입받아 Principal을 Long타입으로 캐스팅해 userId를 얻는 과정은 매우 불편
이를 커스텀 어노테이션으로 해결함
- Long 타입 파라미터에 붙이면 현재 사용자의 인증정보(id)를 주입해줌
추후 인증 방식이 userId를 직접 SecurityContext에 넣는 방식이 아니게 된다면 리팩토링 필요
> [FEAT] LoginUserId 커스텀 어노테이션 구현

- frontend/techpick/src/components/FolderTree/FolderDropZone.tsx
- frontend/techpick/src/components/FolderTree/FolderInfoItem.tsx
- frontend/techpick/src/components/FolderTree/folderInfoItem.util.ts
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- frontend/techpick/src/stores/dndTreeStore/treeMockDate.ts
- Close #358 
- issue : #358 
- 이전엔 multi select 이후에 정렬이 이전과 달리졌습니다. 그를 이번 과정에서 수정했습니다.
https://github.com/user-attachments/assets/eeb3ad1b-5b68-468b-bf6b-2eff855b1275
https://github.com/user-attachments/assets/5cfa2b9c-8c11-4ed5-84fb-d92dabeb3349
> [FIX] drag & drop 후 정렬 변경

- backend/docker-compose.yaml
- backend/techpick-api/src/main/java/techpick/api/config/SwaggerConfig.java
- backend/techpick-core/src/main/resources/application-core.yaml
- backend/techpick-security/src/main/java/techpick/security/config/SecurityConfig.java
- backend/techpick-security/src/main/java/techpick/security/handler/OAuth2SuccessHandler.java
- backend/techpick-security/src/main/java/techpick/security/util/CookieUtil.java
- backend/techpick-security/src/main/resources/application-security.yaml
- Close #378
- 기능 : local-dev-prod 설정 분리
- issue : #378
환경별 설정 분리
`core.base-url: http://localhost:8080`
`security.clientUrl: https://local.minlife.me:3000`
`security.cookie-domain: localhost`
`security.default-redirect-url: http://localhost:8080`
`core.base-url: https://api.minlife.me`
`security.clientUrl: https://app.minlife.me`
`security.cookie-domain: minlife.me`
`security.default-redirect-url: https://local.minlife.me`
`core.base-url: https://api.techpick.org`
`security.clientUrl: https://app.techpick.org`
`security.cookie-domain: techpick.org`
`security.default-redirect-url: https://app.techpick.org`
---
docker-compose.yml 은 local 프로파일을 설정하도록 되어있으니 필요한 경우 수정
현재 application-core.yaml에서 mysql url이 docker network안에서 돌게 해놔서
intellij에서 실행하면 db 연결 안되고 docker-compose로 실행해야함
1. gradle build …
> [REFACTOR] local-dev-prod 설정 분리

- backend/build.gradle
- backend/techpick-api/build.gradle
- backend/techpick-api/src/main/java/techpick/api/application/folder/controller/FolderApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/tag/controller/TagApiController.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/tag/TagDataHandler.java
- backend/techpick-security/src/main/java/techpick/security/annotation/LoginUserId.java
- Close #382
- 기능 : Folder, Tag 리팩토링
- issue : #382
DB 상에는 user의 태그 리스트 순서가 제대로 들어가는 것은 확인.
유저의 태그 리스트 조회 시 순서가 제대로 보장되지 않아 조회하는 부분에서 순서 보장되도록 해결
-> `@LoginUserId`에 `@Schema(hidden = true)`로 변경
> [REFACTOR] Folder, Tag 리팩토링

- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/dto/FolderMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/dto/FolderResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderService.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickCommand.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/folder/FolderDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/tag/TagDataHandler.java
- backend/techpick-api/src/test/java/techpick/api/domain/pick/service/PickServiceTest.java
- backend/techpick-core/src/main/java/techpick/core/model/folder/Folder.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/Pick.java
- Close #386
- 기능 : 폴더 멀티 이동 관련 버그 수정, Pick, Folder 리팩토링
- issue : #386
- Pick Entity, Dto
`tagOrderList` -> `tagIdOrderedList`로 변경
- Folder Entity, Dto 
`childFolderOrderList` -> `childFolderIdOrderedList`로 변경
`childPickOrderList` -> `childPickIdOrderedList`로 변경
- 변경 전 : 픽 생성, 수정 시 태그가 없어도 픽이 생성되는 문제 발생
- 변경 후 : 픽 생성, 수정 시 태그가 존재하는지 검증하는 로직 추가 
- 변경 전 : ArrayList `가장 마지막 인덱스`에 추가
- 변경 후 : ArrayList `0번 인덱스`에 추가
`Folder.java`
```java
public void addChildPickIdOrderedList(Long pickId) {
childPickIdOrderedList.add(0, pickId);
}
public void addChildFolderIdOrderedList(Long folderId) {
childFolderIdOrderedList.add(0, folderId);
}
```
`FolderService.java`
```java
@Transactional
public void moveFolder(FolderCommand.Move command) {
List<Folder> folderList = …
```
> [REFACTOR] 폴더 멀티 이동 관련 버그 수정, Pick, Folder 변수명 통일

- backend/techpick-api/src/main/java/techpick/api/application/folder/controller/FolderApiConstant.java
- backend/techpick-api/src/main/java/techpick/api/application/folder/controller/FolderApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/folder/FolderDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/folder/Folder.java
- Close #395 
- 기능 : 다른 폴더로 이동되지 않는 문제, 스웨거 응답 예시 추가
- issue : #395 
`FolderApiResponse` : 변수에 `@Schema(example = "GENERAL")` 명시
`FolderApiController` : `@ExampleObject` 사용하여 응답 예시 구체화
```java
@GetMapping
@Operation(summary = "루트 폴더와 하위 리스트 조회", description = "사용자의 루트 폴더와 루트 하위 전체 폴더를 조회합니다.")
@ApiResponses(value = {
@ApiResponse(responseCode = "200",
description = "조회 성공",
content = @Content(
mediaType = "application/json",
examples = @ExampleObject(value = FolderApiConstant.ROOT_FOLDER_EXAMPLE)
)),
@ApiResponse(responseCode = "401", description = "본인 폴더만 조회할 수 있습니다.")
})
```
`@ExampleObject`에 사용되는 문자열 Json을 컨트롤러에 작성하다보니 너무 지저분해지고 있습니다.
클래스(`FolderApiConstant`) 따로 분리하여 `클래스 내부에 상수로 정의`하여 사용하도록 하였습니다.
우선 하나의 api에만 적용하고, 프론트 측에서 필요로 할 때 추가로 작성하는 것으로 하겠습니다.
기존에 `FolderService`에서 같은 폴더로만 이동이 …
> [FIX] 다른 폴더로 이동되지 않는 문제, 스웨거 응답 예시 추가

- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickBulkService.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickBulkDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickBulkRepository.java
- backend/techpick-api/src/test/java/techpick/api/domain/pick/service/PickBulkInsertTest.java
- Close #407 
- 기능 : pick bulk insert 구현 및 테스트 작성
- issue : #407 
- insert 10000번 vs bulk insert 1번에 대한 시간 소요 측정
- JPA에서 bulk insert를 지원하지 않아 `JdbcTemplate`을 사용하여 구현
- #408 측정 결과 참고
PickBulkRepository 위치가 infrastructure에 위치하고 있습니다. core 쪽으로 이동시키는게 맞을까요?
> [FEAT] pick bulk insert 구현 및 테스트 작성

- backend/techpick-api/src/main/java/techpick/api/config/SwaggerConfig.java
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiErrorResponse.java
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiExceptionHandler.java
- backend/techpick-core/src/main/resources/application-core.yaml
- backend/techpick-security/src/main/java/techpick/security/config/SecurityConfig.java
- backend/techpick-security/src/main/java/techpick/security/config/SecurityProperties.java
- backend/techpick-security/src/main/java/techpick/security/util/CookieUtil.java
- backend/techpick-security/src/main/resources/application-security.yaml
- Close #426 #390
- 기능 : 시큐리티 및 예외처리 리팩토링
- issue : #426 #390
---
- request에서 삭제하려는 쿠키가 존재하는지 확인하여 maxAge를 0으로 변경
- 삭제하려는 쿠키 이름으로 maxAge = 0인 쿠키를 덮어씌움
- request에 쿠키가 포함되어있지 않았다면 삭제가 안되는 문제 발생
- env에서 `TECHPICK_BASE_URL`을 주입받아 활용
- 해당 base-url를 사용하는곳이 spring security관련 설정 뿐이라 application-security.yaml로 하드코딩 예정
- 해당 값은 local/dev/prod에서 모두 변경되어야하는 값인데 환경변수로 주입받으면 프로파일마다 따로 설정해야해서 관리가 번거로움
기존에는 Json 형식에 오류가 있어 파싱 실패시 500에러가 발생
-> 프론트에서 예외처리 하기 힘듬
- Json 파싱 실패 시 발생하는 HttpMessageNotReadableException을 처리할 수 있는 ExceptionHandler 추가
- INVALID_JSON_ERROR 추가
> [REFACTOR] 시큐리티 및 예외처리 리팩토링

- backend/techpick-api/src/main/java/techpick/api/application/folder/controller/FolderApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/dto/FolderCommand.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/exception/ApiFolderErrorCode.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/exception/ApiFolderException.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/folder/FolderDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/folder/FolderRepository.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/Pick.java
- Close #431
- 기능 : FolderService 로직 변경
- issue : #431 
`saveFolder` : 부모 폴더가 본인 소유인지 검증하는 로직 추가
`moveFolder` : 이동하려는 폴더들의 부모폴더가 동일한지 검증하는 로직 추가
폴더 이동 시 이동하는 폴더들의 parentFolderId를 같이 보내줘야합니다. @dmdgpdi 
```
public record Move(
Long userId,
List<Long> idList,
Long parentFolderId, // 추가됨
Long destinationFolderId,
int orderIdx
) {
}
```
기존 : 폴더 삭제 시 모든 하위폴더와 픽들이 삭제됨
변경 : 폴더 삭제 시 모든 하위폴더는 삭제되고 픽들은 휴지통으로 이동됨
> [FIX] FolderService 로직 변경

- frontend/schema/schema.d.ts
- frontend/techpick/src/apis/folder/deleteFolder.ts
- frontend/techpick/src/components/DragOverlay.tsx
- frontend/techpick/src/components/FolderAndPickDndContextProvider.tsx
- frontend/techpick/src/components/FolderTree/FolderDraggable.tsx
- frontend/techpick/src/components/PickListViewer/PickDnDCard.tsx
- frontend/techpick/src/components/dragOverlay.css.ts
- frontend/techpick/src/hooks/useGetDndContextSensor.ts
- frontend/techpick/src/hooks/usePickToPickDndMonitor.tsx
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- frontend/techpick/src/utils/getElementById.ts
- frontend/techpick/src/utils/index.ts
- Close #441
- 기능 :
- issue : #441
- 폴더 삭제 시에 폴더 이동api를 사용하는 것이 아닌 폴더 삭제 api를 사용합니다.
- 이전과 달리 multi-select 시에 첫번째 요소가 아닌 다른 요소를 드래그해도 자연스럽게 드래그 됩니다.
https://github.com/user-attachments/assets/93d59251-5959-4124-9de9-33507a27fa7f
https://github.com/user-attachments/assets/864f0616-1fcb-4665-81e5-ea5ec989cd8b
> [FIX] DragOver 수정 및 휴지통 이동 로직 변경

- frontend/techpick/src/components/FolderTree/FolderListItem.tsx
- frontend/techpick/src/styles/reset.css.ts
- Close #445 
- 기능 :
- issue : #445 
- 포커스된 폴더를 삭제 시에 미분류 페이지로 리다이렉트 됩니다.
> [FIX] 현재 포커스된 폴더 삭제 시에 미분류 페이지로 리다이렉트

- backend/build.gradle
- backend/techpick-api/src/test/java/techpick/api/domain/folder/service/FolderServiceUnitTest.java
- backend/techpick-api/src/test/java/techpick/api/fixture/FolderFixture.java
- backend/techpick-api/src/test/java/techpick/api/fixture/PickFixture.java
- backend/techpick-api/src/test/java/techpick/api/fixture/UserFixture.java
- Close #425
- 기능 : FolderService 단위 테스트 구현
- issue : #425
- 테스트를 위한 `mockito` 의존성 추가
- 단위 테스트를 위한 `Fixture` 클래스 구현
- entity에 추가로 public builder를 정의하지 않아도 builder를 이용해 편하게 테스트용 객체 생성 가능
- FolderService 단위 테스트 구현
Tag, Pick, Auth관련해서도 단위 테스트 작성 필요
> [TEST] FolderService 단위 테스트 구현

- backend/techpick-api/src/main/resources/logback-spring.xml
- backend/techpick-batch/src/main/resources/logback-spring.xml
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiException.java
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiExceptionHandler.java
- backend/techpick-core/src/main/java/techpick/core/exception/level/ErrorLevel.java
- backend/techpick-core/src/main/java/techpick/core/exception/level/FatalErrorLevel.java
- backend/techpick-core/src/main/java/techpick/core/exception/level/NormalErrorLevel.java
- backend/techpick-core/src/main/java/techpick/core/exception/level/WarningErrorLevel.java
- backend/techpick-core/src/main/java/techpick/core/filter/RequestLoggingFilter.java
- backend/techpick-core/src/main/java/techpick/core/util/CachedHttpServletRequest.java
- backend/techpick-core/src/main/java/techpick/core/util/RequestHolder.java
- Close #480
- 기능 : 에러 요청에 대한 로깅 구현
- issue : #480
기존에는 예외에 대해 에러코드와 메세지만 로깅했지만, 이것으로는 디버깅  및 행동분석에 부족하다고 판단되어
예외 발생 시 해당 요청을 로깅하는 기능을 구현
필터를 구현해 모든 요청을 `CachedHttpServletRequest`에 캐싱하고
`CachedHttpServletRequest`객체를 `ThreadLocal`에 저장
이후 예외가 발생하면, 캐싱한 `CachedHttpServletRequest`를 꺼내와서 요청을 로깅
로깅예시
```
{
"requestTime": "2024-11-18T23:19:08.174014",
"method": "DELETE",
"requestBody": "{\n이건 잘못된 Json 요청입니다.",
"requestURI": "/api/folders",
"cookies": {
"access_token": "(엑세스토큰 값)",
"JSESSIONID": "(세션ID)",
"techPickLogin": "true"
}
}
```
이것 외에도 실제 예외가 발생했을때의 파라미터를 로깅하는 기능 추가 필요
> [FEAT] 에러 요청에 대한 로깅 구현

- frontend/techpick/src/app/(signed)/folders/unclassified/page.tsx
- frontend/techpick/src/components/DragOverlay.tsx
- frontend/techpick/src/components/PickListViewer/DraggablePickListViewer.tsx
- frontend/techpick/src/components/PickListViewer/PickDnDCardListLayout.tsx
- frontend/techpick/src/components/PickListViewer/PickDndRecord.tsx
- frontend/techpick/src/components/PickListViewer/PickDndRecordListLayout.tsx
- frontend/techpick/src/components/PickListViewer/PickListSortableContext.tsx
- frontend/techpick/src/components/PickListViewer/PickListViewerInfiniteScroll.tsx
- frontend/techpick/src/components/PickListViewer/PickRecordListLayout.tsx
- frontend/techpick/src/components/PickListViewer/pickRecordListLayout.css.ts
- frontend/techpick/src/stores/index.ts
- frontend/techpick/src/stores/pickRenderModeStore.ts
- frontend/techpick/src/stores/pickRenderModeStore.type.ts
- frontend/techpick/src/types/PickRenderModeType.ts
- frontend/techpick/src/types/index.ts
- Close #491 
- 기능 :
- issue : #491 
- card 형태에서 list 형태로 변경했습니다.
- 렌더링 모양을 결정하는 중앙 스토어를 추가했습니다.
> [FEAT] 픽 렌더링 카드에서 리스트 아이템으로 교체

- backend/techpick-api/src/main/java/techpick/api/application/folder/controller/FolderMigrationController.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/dto/FolderCommand.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderMigrationService.java
- Close #495
- 기능 : 폴더 export 기능 구현
- issue : #495
본인의 폴더와 픽들을 크롬에 import 가능한 html형식으로 다운로드 받습니다.
- `/api/folders/export` : 본인의 모든 폴더(미분류, 휴지통 포함)를 추출합니다.
- `/api/folders/{folderId}/export` : 특정 폴더 및 하위 폴더/픽들을 추출합니다.
> [FEAT] 폴더 export 기능 구현

- frontend/techpick-extension/src/components/DeselectTagButton.css.ts
- 기능 :
- issue : #
- 익스텐션의 x가 가운데 오게 했습니다.
> [DESIGN] 익스텐션 디자인 변경

- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/application/tag/dto/TagApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/config/ValidationConfig.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/exception/ApiPickErrorCode.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/exception/ApiPickException.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/tag/TagDataHandler.java
- backend/techpick-api/src/main/resources/messages.properties
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiErrorResponse.java
- backend/techpick-core/src/main/java/techpick/core/exception/base/ApiExceptionHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/user/User.java
- Close #487 
- 기능 : 픽 제목 최대 길이 검증 및 Validation 검증 리팩토링, 태그 이동 버그 수정
- issue : #487 
- 픽 생성, 수정 시 제목 최대 길이(200자) 검증 로직 추가
- 현재 Validation 예외는 공통 예외 메시지를 던지고 있음. 각 필드 별 다른 예외 메시지를 던지도록 수정
- Tag 이동 시 리스트 길이보다 큰 인덱스로 이동하려고 할 때 IndexOutOfBoundsException 문제 해결
> [FEAT] 픽 제목 최대 길이 검증 및 Validation 검증 리팩토링

- backend/techpick-api/src/main/java/techpick/api/domain/folder/exception/ApiFolderErrorCode.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/exception/ApiFolderException.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/tag/TagDataHandler.java
- backend/techpick-api/src/main/resources/application.yaml
- backend/techpick-core/src/main/java/techpick/core/model/folder/Folder.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/Pick.java
- Close #493
- 기능 : 픽 리팩토링
- issue : #493
- 원인 : pickTag 테이블 row 삭제할 때 `tagId를 조건으로 삭제`하는 것이 아닌 `pk를 조건으로 삭제`하여 버그 발생
- 해결 : `tagId로 삭제`하도록 변경
- 원인 : 픽 수정할 때 부모, 이동할 `폴더의 픽 리스트를 수정하지 않음`.
- 해결 : 픽 수정할 때 부모, 이동할 `폴더의 픽 리스트 제거, 추가하는 로직` 추가
- 가독성 향상을 위해 리팩토링 진행
- 공통으로 사용되는 로직들 메서드로 분리
- 에러 메세지, 에러 코드명 변경
- `"이동하려는 폴더들의 범위가 올바르지 않음"` -> `"휴지통 또는 미분류 폴더에 폴더를 (생성/이동)할 수 없음"`
- `application.yaml` 확인
- `false`로 두면 접근 불가
- 현재는 `true`로 열어두었음.
> [BUG] 픽 태그 삭제 버그, 픽 수정 버그 수정

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- Close #512 
- 기능 : 픽 태그 리스트 수정 시 데드락 문제 수정
- issue : #512
- 개발 서버에서 테스트를 위한 PR입니다.
- PickService의 updatePick 트랜잭션 제거
- 픽 생성 시 null에 대한 length() 호출 방지
- 데드락 문제 해결되지 않을 시 비관적 락 도입 예정
> [BUG] 픽 태그 리스트 수정 시 데드락 문제 수정

- backend/techpick-api/build.gradle
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/PickTag.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/PickTagRepository.java
- Close #512
- 기능 : PickTag 테이블에 낙관적 락 설정
- issue : #512
- 개발 서버에서 테스트를 위해 PickTag 테이블에 낙관적 락 설정
- 픽의 태그 삭제 시 `ObjectOptimisticLockingFailureException` 발생하여 낙관적 락 설정하고자 함.
> [REFACTOR] PickTag 테이블에 낙관적 락 설정

- frontend/techpick/src/components/TagPicker/TagAutocompleteDialog.tsx
- 기능 :
- issue : #
- 태그 선택이나 선택된 태그 삭제 시에 TagAutocompleteDialog의 위치를 조정하게 했습니다.
> [DESIGN] TagAutocompleteDialog 위치 조정

- frontend/techpick/src/app/(signed)/folders/search/page.tsx
- Close #517 
- 기능 :
최초 로드시에 픽 중복 검색 막았습니다.
디자인의 경우 다른 곳을 먼저 변경한 뒤에 검색 작업이 수행됩니다.
- issue : #517
> [FIX] 검색 픽 중복 표시

- backend/techpick-api/src/main/java/techpick/api/application/link/controller/LinkApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/link/dto/LinkApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/link/dto/LinkApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/link/dto/LinkMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/link/dto/LinkResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/link/service/LinkService.java
- Close #507 
- 기능 : 해당 링크의 Og 태그 데이터 가져오는 API 구현
- issue : #507
- 해당 링크의 Og 태그 데이터 가져오는 API 구현
- 링크에 대한 부분이므로 `LinkApiController`에 API 구현
> [FEAT] 해당 링크의 Og 태그 데이터 가져오는 API 구현

- frontend/techpick/src/components/CreatePickForm/FolderSelect.css.ts
- frontend/techpick/src/components/CreatePickForm/FolderSelect.tsx
- Close #569 
- 기능 :
- issue : #569 
zIndex추가해서 이쁘게 함
> [DESIGN] 픽 생성시 zIndex추가

- backend/techpick-api/src/main/java/techpick/api/infrastructure/folder/FolderDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/folder/Folder.java
- Close #574
- 기능 : 폴더 삭제 Folder 엔티티 내부 메서드 활용하도록 변경
- issue : #574
- FolderDataHandler의 폴더 삭제 메서드에서 부모 폴더 삭제하는 부분 폴더 내부 메서드 사용하도록 변경
> [BUG] 부모 폴더 삭제 Folder 엔티티 내부 메서드 활용하도록 변경

- backend/techpick-core/src/main/java/techpick/core/util/MeasureTimeAspect.java
- Close #573
- 기능 : @MeasureTime 어노테이션 버그 수정
- issue : #573
- 원인 : 반환 타입이 `void`로 되어있어 반환값이 컨트롤러로 넘어가지 않음
```
@Around("pointcut()")
public void around(ProceedingJoinPoint joinPoint) throws Throwable {
var methodName = joinPoint.getSignature().getName();
// 필요하다면 StopWatch 클래스 도입 고려
long startTime = System.currentTimeMillis();
joinPoint.proceed();
long endTime = System.currentTimeMillis();
log.info("{} 실행 시간 : {} ms", methodName, endTime - startTime,);
}
```
- 수정 : 반환값을 `Object`타입으로 반환
```
@Around("pointcut()")
public Object around(ProceedingJoinPoint joinPoint) throws Throwable {
var methodName = joinPoint.getSignature().getName();
// 필요하다면 StopWatch 클래스 도입 고려
long startTime = System.currentTimeMillis();
var result = joinPoint.proceed();
long endTime = System.currentTimeMillis(); …
```
> [FIX] @MeasureTime 어노테이션 버그 수정

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickCommand.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickSearchService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickQuery.java
- backend/techpick-api/src/test/java/techpick/api/domain/pick/service/PickSearchTest.java
- Close #586
- 기능 : 페이지네이션 적용되지 않은 검색 API 구현
- issue : #586
태그 검색 조차 없기 때문에 적어도 태그는 필터링할 수 있도록 하기 위해서 API 구현
페이지네이션을 적용되지 않은 API 구현 이유는 프론트 쪽 무한 스크롤 관련 에러 처리가 시간 소요가 크기 때문
- 페이지네이션 적용되지 않은 API 구현
- `/api/picks/search/all` : 페이지네이션 처리x
- `/api/picks/search` : 페이지네이션 처리
- 페이지네이션 처리된 부분과 아닌 부분 메서드, 변수명 변경
- `searchPick` : 페이지네이션 처리x
- `searchPickPagination` : 페이지네이션 처리
> [FEAT] 페이지네이션 적용되지 않은 검색 API 구현

- frontend/techpick/src/components/DragOverlay.tsx
- frontend/techpick/src/components/PickDragOverlayShadowList.tsx
- frontend/techpick/src/components/dragOverlay.css.ts
- frontend/techpick/src/components/pickDragOverlayShadowList.css.ts
- frontend/techpick/src/hooks/index.ts
- frontend/techpick/src/hooks/useGetDragOverStyle.ts
- Close #594 
- 기능 :
- issue : #
- pick을 drag 시의 디자인을 변경했습니다.
https://github.com/user-attachments/assets/5483adce-e797-4bcf-ae8c-5c845a2f925a
https://github.com/user-attachments/assets/f9d4566e-e0ea-4ec2-9ea2-b1ccbeca28ef
> [DESIGN] 픽 드래그 시의 디자인 개선

- backend/techpick-api/src/main/java/techpick/api/application/sharedFolder/controller/SharedFolderApiController.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/service/SharedFolderService.java
- Close #607
- 기능 : SharedFolder 리팩토링
- issue : #607
공유폴더에 대한 정보를 json으로 응답해서
해당 json에 대한 schema 정보가 존재하지 않음
이를위해 생성시에는 직렬화 이전의 dto를 내려보네 swagger에 schema 등록
등록된 스키마 목록
- `techpick.api.application.sharedFolder.dto.SharedFolderApiRequest$Create`
- `techpick.api.domain.sharedFolder.dto.FolderNode`
- `techpick.api.domain.sharedFolder.dto.PickNode`
- `techpick.api.domain.sharedFolder.dto.TagNode`
> [REFACTOR]  SharedFolder 리팩토링

- frontend/techpick/src/components/PickTagPicker/PickTagAutocompleteDialog.tsx
- frontend/techpick/src/components/PickTagPicker/PickTagPicker.tsx
- frontend/techpick/src/components/PickTagPicker/pickTagAutocompleteDialog.css.ts
- frontend/techpick/src/components/SelectedTagListLayout/SelectedTagListLayout.css.ts
- frontend/techpick/src/components/pickDraggableListLayout.css.ts
- Close #606 
- 기능 :
- issue : #606 
- PickTagPicker의 렌더링이 해결되었습니다.
- 이제 아래의 남은 영역에 따라 적절하게 렌더링 됩니다. 이전과 달리 순서가 꼬이지 않습니다.
이번 PR에서의 변경점
| <img width="1104" alt="스크린샷 2024-11-27 오후 9 03 04" src="https://github.com/user-attachments/assets/2594fa62-e728-4c2a-ab89-cd72a894f1a2"> | <img width="1112" alt="스크린샷 2024-11-27 오후 9 02 31" src="https://github.com/user-attachments/assets/4adfbd35-bbd6-4186-8020-f91f86d97e0f">|
| <img width="393" alt="스크린샷 2024-11-26 오후 8 55 07" src="https://github.com/user-attachments/assets/fc058ef1-2ccd-4f6a-9c79- …
> [FIX] PickTagPicker 망가지는 UI 해결

- frontend/techpick/src/app/(signed)/folders/[folderId]/page.tsx
- frontend/techpick/src/app/(signed)/folders/recycle-bin/page.tsx
- frontend/techpick/src/app/(signed)/folders/unclassified/page.tsx
- frontend/techpick/src/components/FolderLoadingPage.tsx
- frontend/techpick/src/components/FolderTree/HorizontalResizableContainer.tsx
- frontend/techpick/src/hooks/index.ts
- frontend/techpick/src/hooks/useClearSelectedPickIdsOnMount.ts
- frontend/techpick/src/hooks/useFetchPickRecordByFolderId.ts
- frontend/techpick/src/stores/pickStore/pickStore.ts
- frontend/techpick/src/stores/pickStore/pickStore.type.ts
- frontend/techpick/src/types/FetchRequestType.ts
- frontend/techpick/src/types/pick.type.ts
- frontend/techpick/src/utils/getOrderedPickListByFolderId.ts
- frontend/techpick/src/utils/index.ts
- Close #613 
- 기능 :
- issue : #613 
- 로딩상태와 값이 비어있을 때의 상태를 구분할 수 있습니다. 
- 현재 folderId를 이용해 pick을 받아오는 걸 중앙 스토어에서 직접 호출하지 않고 hook을 이용해서 호출합니다.
> [FEAT] pick 로딩중인지, 빈 값인지 확인하는 로직 추가

- frontend/techpick/src/components/FolderTree/FolderContextMenu.tsx
- frontend/techpick/src/components/FolderTree/FolderListItem.tsx
- frontend/techpick/src/components/FolderTree/MoveFolderToRecycleBinDialog.tsx
- frontend/techpick/src/components/FolderTree/TreeNode.tsx
- frontend/techpick/src/components/FolderTree/moveFolderToRecycleBinDialog.css.ts
- frontend/techpick/src/hooks/index.ts
- frontend/techpick/src/hooks/useDisclosure.ts
- Close #623 
- 기능 :
dialog의 open 상태를 관리하는 useDisclosure hook  구현
기존의 context menu 및 dialog가 drag안되게 수정
- issue : #623
> [FIX] 폴더 콘텍스트 및 다이얼로그 수정 및 공통 hook 생성

- frontend/schema/schema.d.ts
- frontend/techpick/src/apis/apiConstants.ts
- frontend/techpick/src/apis/eventLog/index.ts
- frontend/techpick/src/apis/eventLog/postClickedLinkUrl.ts
- frontend/techpick/src/components/PickRecord/PickRecord.tsx
- frontend/techpick/src/hooks/useOpenUrlInNewTab.ts
- frontend/techpick/src/types/PostClickedLinkUrlResponseType.ts
- frontend/techpick/src/types/index.ts
- Close #652 
- 기능 :
-  링크를 클릭할 때마다 이벤트를 수집하는 api를 호출합니다. 실패시에는 아무런 에러를 띄우지 않습니다.
- issue : #652 
- error의 경우 apiClient에서 핸들링할 예정입니다. 또한 get요청이 실패할 경우 error boundary를 추가해서 에러를 다룰 예정입니다. 이는 #651 작업에서 하겠습니다.
> [FEAT] 링크 클릭 시에 이벤트 수집 추가

- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiRequest.java
- backend/techpick-api/src/main/resources/messages.properties
- Close #592
- 기능 :  폴더 제목 최대 길이 100자로 제한
- issue : #592
- 폴더 제목 최대 길이 제한 : 100자
> [REFACTOR] 폴더 제목 최대 길이 제한

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiMapper.java
- Close #681 
- 기능 : 픽 검색 API 스웨거에 타입 명시적으로 변경
- issue : #681
- `@ModelAttribute`로 변경했던 픽 API가 스웨거에 타입이 제대로 명시되지 않음.
- 다시 `@RequestParam`으로 변경
> [REFACTOR] 픽 검색 API 스웨거에 타입 명시적으로 변경

- backend/techpick-api/src/main/java/techpick/api/application/ranking/controller/RankingApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/LinkInfoWithViewCount.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/RankingApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/RankingByViewCount.java
- backend/techpick-api/src/main/java/techpick/api/config/HttpApiConfiguration.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/RankingBasedStrategy.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/ranking/RankingApi.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/ranking/RankingRepository.java
- Close #697
url과 count만 반환하던 랭킹 정보에, 링크 OG 태그 정보도 함께 반환합니다.
- 기능 : 기존 랭킹 조회 결과에 Link OG 태그 정보도 포함
- issue : #697
> [FIX] 랭킹 정보에 링크 OG 태그 정보 추가 

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/service/FolderService.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- Close #734
- 기능 : 추천 링크로 부터 픽 생성 API 구현
- issue : #734
추천 페이지에서 dnd로 픽 생성시 이미 존재하는 픽일 경우 단순 오류메세지만 발생
중복된 픽일 경우 해당 폴더로 이동하는 메세지가 나오는 것이 사용자 경험에 더 좋을것으로 판단되어 전용 api 구현
ex) 이미 등록된 픽입니다. 해당 폴더로 이동하겠습니까? yes / no
- `exist` : 이미 존재하는 픽인지 여부 (`true`/`false`)
- `pick` : 새로 생성되거나 기존에 있는 픽 정보
- `parentFolder` : 픽의 부모 폴더 정보
> [FEAT] 추천 링크로 부터 픽 생성 API 구현

- frontend/techpick/src/components/PickRecord/PickDraggableRecord.tsx
- frontend/techpick/src/components/Search2/FilterOptions.tsx
- frontend/techpick/src/components/Search2/FilterToggleContainer.tsx
- frontend/techpick/src/components/Search2/HoverCard.tsx
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- frontend/techpick/src/components/Search2/SearchInput.tsx
- frontend/techpick/src/components/Search2/filterOptions.css.ts
- frontend/techpick/src/components/Search2/hoverCard.css.ts
- frontend/techpick/src/components/Search2/searchDialog.css.ts
- frontend/techpick/src/hooks/useSearchElementId.ts
- frontend/techpick/src/utils/checkImageUrlByUrl.ts
- Close #728
- 기능 : 이슈에 언급된 검색모달에서 넘어간 페이지의 픽 하이라이트를 클릭 이벤트 발생시 사라지게 했습니다.
- 이외에 @kimminkyeu 님이 말씀해주신 검색 다이얼로그 내 스타일을 수정했습니다.
- issue : #728
이번 PR에서의 변경점
| ![Before Image](https://private-user-images.githubusercontent.com/97217713/394175283-37447f26-9116-408a-9124-f5c43f9303b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTk0MjQsIm5iZiI6MTczMzg5OTEyNCwicGF0aCI6Ii85NzIxNzcxMy8zOTQxNzUyODMtMzc0NDdmMjYtOTExNi00MDhhLTkxMjQtZjVjNDNmOTMwM2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyU …
> [FIX] 검색 결과 포커스 해제

- backend/build.gradle
- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/controller/RankingApiController.java
- backend/techpick-api/src/main/java/techpick/api/config/HttpApiConfiguration.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickBulkService.java
- backend/techpick-core/src/main/java/techpick/core/config/CacheConfig.java
- backend/techpick-core/src/main/java/techpick/core/model/cache/CacheType.java
- backend/techpick-ranking/src/main/java/techpick/ranking/application/RankingController.java
- backend/techpick-ranking/src/main/java/techpick/ranking/domain/pick/PickRankingService.java
- backend/techpick-ranking/src/main/java/techpick/ranking/exception/ApiRankErrorCode.java
- backend/techpick-ranking/src/main/java/techpick/ranking/exception/ApiRankException.java
- Close #738
- 기능 : Caffein Cache 구현 및 랭킹 로직에 캐싱 처리
- issue : #738
- 사용 이유 1 : 분산 환경이면 Redis를 두어서 여러 서버에서 하나의 캐시를 사용하면 되지만, 우리는 분산 환경이 아니므로 속도가 더 빠른 로컬 캐시 채택하였음.
- 사용 이유 2 : 로컬 캐시 중에 가장 성능이 좋음. 캐싱의 가장 큰 목적은 Read이므로 Read 성능도 가장 뛰어난 Caffeine 사용
- 랭킹 관련 서비스에 캐싱 처리
- 일간, 주간, 월간 별로 캐시가 다르기 때문에 사용하던 메서드 랭킹 메서드 `getLinksOrderByViewCount` 2개로 분리
- end_date - start_date == 1이면 일간 캐시 적용, 아니면 주간 캐시 적용
- 월간 캐시는 따로 Api 있으므로 따로 적용
- 일간 캐시 : 1시간 간격으로 업데이트
- 주간 캐시 : 24시간 간격으로 업데이트
- 월간 캐시 (픽 랭킹) : 3시간 간격으로 업데이트
- 픽 bulk insert시 부모 폴더의 ChildPickList에 add해주지 않는 문제가 있어 수정
> [FEAT] Caffein Cache 구현 및 랭킹 로직에 캐싱 처리

- frontend/techpick/src/components/FolderTree/FolderLinkItem.tsx
- frontend/techpick/src/components/FolderTree/FolderListItem.tsx
- frontend/techpick/src/components/FolderTree/FolderTreeHeader.tsx
- frontend/techpick/src/constants/index.ts
- frontend/techpick/src/constants/nonExistFolderId.ts
- frontend/techpick/src/stores/pickStore/pickStore.ts
- frontend/techpick/src/stores/pickStore/pickStore.type.ts
- Close #762 
기능 : Post보다 Get요청이 먼저 가서 발생하는 문제를 해결했습니다. 이제 픽을 이동한 폴더는 픽 이동이 수행된 후에 이동이 됩니다.
issue : 
- #762 
https://github.com/user-attachments/assets/6bc7ec36-00cf-4a3b-a944-47670966d4c6
> [FIX] 다른 폴더로 픽 이동 후 이동한 폴더 클릭 시 화면에 나타나지 않는 문제 수정

- frontend/techpick-extension/src/chrome-extension/background.ts
- frontend/techpick-extension/src/chrome-extension/manifest.json
- frontend/techpick-extension/src/components/CreatePickForm.tsx
- frontend/techpick-extension/src/components/DeleteTagDialog.tsx
- frontend/techpick-extension/src/components/SkeltonPickForm.tsx
- frontend/techpick-extension/src/components/TagAutocompleteDialog.tsx
- frontend/techpick-extension/src/components/UpdatePickForm.tsx
- frontend/techpick-extension/src/stores/tagStore.ts
- frontend/techpick-extension/src/stores/tagStore.type.ts
- Close #786 
- 기능 :
- issue : #786 
- #767
- #766 
- #755 
- 이제 익스텐션에서 태그를 백 스페이스키로 지울 수 있습니다.
- techpick에서 baguni로 이름을 수정했습니다.
- 태그 취소도 엔터키를 누르면 동작되게 변경했습니다.
- 우클릭을 누르면 생기는 컨텍스트 메뉴에서 baguni로 곧바로 이동할 수 있습니다.
-  버그를 발견하셨거나 사용성에 문제가 있을 시에 바로 말씀해주시면 수정하겠습니다.
- production api가 https가 되면 바로 크롬 익스텐션 스토어에 제출하겠습니다.
> [FEAT] 익스텐션 수정

- frontend/techpick/src/app/(signed)/mypage/page.tsx
- Close #783 
- 기능 :
- issue : #783 
- 기본 폴더가 아닌 사용자가 만든 폴더에서 마이 페이지로 이동할 때, 포커싱이 유지되는 문제를 수정했습니다.
> [FIX] 폴더 이동 후 포커싱 문제 수정

- frontend/techpick/src/app/(unsigned)/login/failed/page.css.ts
- frontend/techpick/src/app/(unsigned)/login/failed/page.tsx
- Close #744 
- 기능 :
- 로그인 실패 UI를 추가했습니다.  (로그인 화면과 동일하고 실패했다는 글자만 추가되었습니다.)
- issue : #744
> [FEAT] 로그인 실패 UI 추가

- frontend/techpick/src/components/RecommendedPickCarousel/PickCarouselCard.tsx
- frontend/techpick/src/components/RecommendedPickCarousel/pickCarouselCard.css.ts
- Close #802 
- 기능 :
- issue : #802 
- vercel의 배포 환경에서 Image 컴포넌트로 캐싱된 이미지가 잘못 불러와지는 걸 확인했습니다. 따라서 일반 img컴포넌트로 바꿔 테스트해봅니다.
> [FIX] Image컴포넌트 대신 img 적용

- frontend/techpick-extension/src/components/DeselectTagButton.tsx
- frontend/techpick-extension/src/components/TagAutocompleteDialog.tsx
- 기능 :
배포된 후에 발견된 버그가 존재했습니디.
1. 이미 존재하는 tag가 보이는 문제(생성은 할 수 없었음) 
2. 태그를 백스페이로 지울 때 글자가 하나 남아있음에도 같이 지울 수 있었음. (''일때 백 스페이스를 누를 때 태그가 없어져야하지만 'a'일때 백스페이스를 누르면 태그가 같이 지워졌습니다.
---
해당 문제는 tag가 생성될 때, 값을 초기화하는 것
`onkeyUp` 대신 `onKeyDown` 이벤트로 변경하여 수정했습니다.
> [FIX] 익스텐션 버그 hotfix

- backend/baguni-api/src/main/java/baguni/api/infrastructure/pick/PickDataHandler.java
- Close #833
- 기능 : 픽 제목 수정 시 픽 리스트 순서가 변경되는 문제
- issue : #833
- 기존에 사용하던 픽 수정 API 수정이 이루어지지 않음.
- 기존에 픽 수정 API에서 픽 이동까지 한 번에 했었습니다. 
- 그로 인해 부모 폴더의 자식 픽 리스트가 수정되는 문제가 발생 (삭제 후 삽입하여 리스트의 첫 번째로 이동됨)
- 관련 로직이 남아있었어서 이동과 관련된 로직을 삭제하여 해결하였습니다.
> [BUG] 픽 제목 수정 시 픽 리스트 순서가 변경되는 문제

- backend/baguni-core/src/main/java/baguni/core/model/link/Link.java
- Close #858 
DB에는 image_url이 text로 되어 있지만, JPA 엔티티는 TEXT가 아니기 때문에 
이를 수정하였습니다.
> [CHORE] JPA 링크 엔티티 image_url을 TEXT로 변경

- .github/workflows/baguni.test.api.deploy.yml
- .github/workflows/baguni.test.batch.deploy.yml
- .github/workflows/baguni.test.ranking.deploy.yml
- Close #865 
- 기능 : 
1. 도커 이미지 정리 코드를 배포 스크립트에서 제거함.
2. 서버 내 crontab으로 도커 이미지 정리 스케쥴 등록
- issue : #865 
- 참고 
https://alexgallacher.com/prune-unused-docker-images-automatically/
> [FIX] 배포 스크립트에서 도커 이미지 정리 코드 제거

- frontend/techpick/src/app/(signed)/mypage/page.css.ts
- frontend/techpick/src/components/CreatePickPopover/createPickPopoverButton.css.ts
- frontend/techpick/src/components/DragOverlay/FolderItemOverlay.tsx
- frontend/techpick/src/components/DragOverlay/PickRecordOverlay.tsx
- frontend/techpick/src/components/DragOverlay/folderItemOverlay.css.ts
- frontend/techpick/src/components/DragOverlay/pickRecordOverlay.css.ts
- frontend/techpick/src/components/FolderTree/MoveFolderToRecycleBinDialog.tsx
- frontend/techpick/src/components/FolderTree/ShareFolderDialog.tsx
- frontend/techpick/src/components/FolderTree/moveFolderToRecycleBinDialog.css.ts
- frontend/techpick/src/components/FolderTree/shareFolderDialog.css.ts
- frontend/techpick/src/components/ImportBookmarkDialog.tsx
- frontend/techpick/src/components/MyPage/myPageShareFolderField.css.ts
- frontend/techpick/src/components/PickTagPicker/DeleteTagDialog.css.ts
- frontend/techpick/src/components/PickTagPicker/PickTagAutocompleteDialog.tsx
- frontend/techpick/src/components/PickTagPicker/pickTagAutocompleteDialog.css.ts
- frontend/techpick/src/components/PickTagPicker/showDeleteTagDialogButton.css.ts
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- frontend/techpick/src/components/Search2/searchDialog.css.ts
- frontend/techpick/src/components/TutorialDialog.tsx
- frontend/techpick/src/components/importBookmarkDialog.css.ts
- frontend/techpick/src/components/tutorialDialog.css.ts
- frontend/techpick/src/styles/baseButtonStyle.css.ts
- frontend/techpick/src/styles/dialogStyle.css.ts
- frontend/techpick/src/styles/goldButtonStyle.css.ts
- frontend/techpick/src/styles/greenButtonStyle.css.ts
- frontend/techpick/src/styles/orangeButtonStyle.css.ts
- frontend/techpick/src/styles/redButtonStyle.css.ts
- frontend/techpick/src/styles/sandButtonStyle.css.ts
- Close #864 
- 기능 :
- issue : #864 
개발하며 발생하던 중복 코드를 제거했습니다.
- 버튼 스타일을 공통 스타일로 추출했습니다. 현재 사용하는 outline 스타일 외에도 solid, ghost, link의 버튼 스타일을 추가했습니다. 색만 지정해주므로 width와 height, padding등의 스타일은 직접 추가해서 사용해야합니다. (chakra ui를 참고했습니다. [참고링크](https://v2.chakra-ui.com/docs/components/button#button-variants))
- 다이얼로그 스타일을 공통 스타일로 추출했습니다. `dialogOverlayStyle`과 `dialogContentStyle`로 공통 추출했습니다. `dialogContentStyle`도 버튼과 마찬가지로 width와 height, padding등의 공간은 직접 추가해서 사용해야합니다.
- dragOverlay의 중복성도 제거했습니다. `PickRecord` 컴포넌트를 예시로 들면 `PickRecord`를 수정하면 `PickRecordOverlay`의 style도 변경해야했는데 이제 `PickRecord`을 수정하면 `PickRecordOverlay`도 동일한 적용을 받게 됩니다.
- 커밋을 조금 보기 힘들게 해서 커밋별로 보는 것이 아니라 PR별로 코드를 보는 것이 좋을 것 같습니다!
> [REFACTOR] 중복 스타일링 제거

- backend/baguni-api/src/main/java/baguni/api/domain/link/service/LinkService.java
- Close #874
- 기능 : og:image 파싱 로직 수정
- issue : #874
- 자바 URL 객체 이용하여 host 뒤에 있는 path name(세부 url) 정보들은 사용하지 않도록 하였습니다.
- 예를 들어, https://blog.dongholab.com/about 경로가 있다면,
- https://blog.dongholab.com 정보만 활용하도록 하였습니다.
- 이미지 url이 상대 경로인 경우
- base_url :  https://blog.dongholab.com
- image_url : /og-image.png
- base_url + image_url
- 결과 값 : https://blog.dongholab.com/og-image.png
> [REFACTOR] og:image 파싱 로직 수정

- frontend/techpick/src/components/DragOverlay/DragOverlay.tsx
- frontend/techpick/src/components/DragOverlay/PickCarouselCardOverlay.tsx
- frontend/techpick/src/components/DragOverlay/PickRecordOverlay.tsx
- frontend/techpick/src/components/DragOverlay/pickRecordOverlay.css.ts
- frontend/techpick/src/components/PickRecord/PickRecord.tsx
- frontend/techpick/src/components/PickRecord/SharePickRecord.tsx
- frontend/techpick/src/components/RecommendedPickCarousel/PickCarouselCard.tsx
- frontend/techpick/src/hooks/index.ts
- frontend/techpick/src/hooks/useImageLoader.ts
- Close #873 
기능
- 이미지가 엑스박스가 뜨던 이유는 존재하지 않는 자원을 찾는 url 혹은 잘못된 url이 존재하기 때문이었습니다. 따라서 해당 url을 불러오는데 실패하고 엑박이 떴었습니다. 따라서 이미지가 error일 때는 default image를 보여줘야 했습니다.
잘못된 url로 이미지를 불려오려다 실패하는 네트워크 통신 예시
- issue : #873 
- `useImageLoader`라는 훅으로 해당 이미지의 상태가 loading 중인지 loaded 됐는지, 에러인지 확인하고 렌더링을 하게 변경했습니다. 
이번 PR에서의 변경점
| ![K-018](https://github.com/user-attachments/assets/25d88e76-997b-4ee4-b2bf-e6c5ed7f9348) | ![K-019](https://github.com/user-attachments/assets/b8d94095-f21e-46dc-88c4-8c14823e716b)|
| ![K-020](https://github.com/user-attachments/assets/f34b2761-d7 …
> [FIX] 잘못된 이미지 url일 때 엑스박스가 표기되는 문제 해결

- backend/baguni-api/src/main/java/baguni/api/domain/link/service/LinkService.java
- backend/baguni-core/src/main/java/baguni/core/lib/opengraph/Metadata.java
- backend/baguni-core/src/main/java/baguni/core/lib/opengraph/OpenGraphReader.java
- Close #878
- 기능 : property 속성에 og 데이터가 없는 경우 name 속성 활용하도록 변경
- issue : #878
- property 속성에 og:image가 없는데 name 속성에 image가 있는 경우가 있습니다.
- 이러한 경우를 위해 property 속성에 og 데이터가 없는 경우 name 속성을 활용하도록 변경하였습니다.
- Jsoup의 `children()` 메서드가 아닌 `select()` 메서드를 사용하는 것으로 변경하였습니다.
> [REFACTOR] property 속성에 og 데이터가 없는 경우 name 속성 활용하도록 변경

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiRequest.java
- backend/baguni-api/src/main/java/baguni/api/domain/link/service/LinkService.java
- backend/baguni-api/src/main/java/baguni/api/domain/pick/dto/PickCommand.java
- backend/baguni-api/src/main/java/baguni/api/domain/pick/dto/PickMapper.java
- backend/baguni-api/src/main/java/baguni/api/domain/pick/service/PickSearchService.java
- backend/baguni-api/src/main/java/baguni/api/domain/pick/service/PickService.java
- backend/baguni-api/src/main/java/baguni/api/infrastructure/pick/PickDataHandler.java
- backend/baguni-api/src/main/java/baguni/api/infrastructure/pick/PickQuery.java
- backend/baguni-core/src/main/java/baguni/core/model/link/Link.java
- backend/baguni-core/src/main/java/baguni/core/model/pick/Pick.java
- Close #870
- 기능 : 미분류로 즉시 북마크 담는 API
- issue : #870
- 사용하지 않는 검색 API 제거
- 픽 중복 허용 (unique index 제거)
- 미분류로 즉시 담도록 구현
1. 클라이언트(익스텐션)에서 `픽 생성 요청`을 보냄
2. Jsoup을 이용하여 `OG 데이터`를 가져온다.
3. OG 데이터와 픽 생성 요청을 활용하여 Pick, Link를 `DB에 저장`한다.
이 방식을 사용했을 때의 문제점은 `API 응답이 1초 이상` 걸린다는 것입니다.
다음 PR에서 API 응답 시간을 줄이기 위해 OG 데이터는 비동기로 처리할 예정입니다.
1. 클라이언트(익스텐션)에서 `픽 생성 요청`을 보냄
2. Pick, Link를 즉시 `DB에 저장`한다.
3. `메세지 큐`로 OG 데이터를 가져오라는 `메세지를 발행`한다.
4. 클라이언트에 `픽이 생성되었다는 응답`을 보내준다.
5. 메세지 큐에서 메세지를 꺼낸 후 Jsoup을 이용하여 `비동기적으로 OG 데이터를 가져온다.`
> [FEAT] 미분류로 즉시 북마크 담는 API 구현

- frontend/techpick/src/components/FolderTree/moveFolderToRecycleBinDialog.css.ts
- frontend/techpick/src/components/FolderTree/shareFolderDialog.css.ts
- frontend/techpick/src/components/PickTagPicker/DeleteTagDialog.css.ts
- frontend/techpick/src/components/Search2/searchDialog.css.ts
- frontend/techpick/src/components/importBookmarkDialog.css.ts
- frontend/techpick/src/components/tutorialDialog.css.ts
- frontend/techpick/src/styles/dialogStyle.css.ts
- 기능 : 
@obvoso 님께서 찾아주신 기존의 검색창의 색이 이상한 것을 발견해주셨습니다.
gold4 색에서 white로 정상 적용됐습니다. 
gold4가 적용되었던 원인은 [composition](https://vanilla-extract.style/documentation/style-composition/)에서 하나의 클래스로 만드면서 나중에 적용되는 `backgroundColor`를 지운 듯 합니다. 
그래서 `dialogContentStyle`에서 `backgroundColor`를 제거했습니다.
이번 PR에서의 변경점
> [FIX] 검색 다이얼로그 색 정상 적용

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiRequest.java
- backend/baguni-api/src/main/java/baguni/api/infrastructure/pick/PickDataHandler.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/dto/PickCommand.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- Close #897 
- 기능 : 기존 익스텐션의 폴더 이동하기 기능을 위해 백엔드 pick api를 버전 다운합니다.
- issue : #897
> fix: 익스텐션 기존 기능 지원을 위한 API 버전 다운

- frontend/techpick/src/hooks/usePickToFolderDndMonitor.tsx
- frontend/techpick/src/hooks/useRecommendPickToFolderDndMonitor.tsx
- Close #816 
- 기능 : 다른 폴더로 북마크 이동 시, 추천 페이지에서 북마크 추가 시 우측 하단에 toast 알림을 추가 했습니다. 
- issue : #816 
https://github.com/user-attachments/assets/f584ca03-94e5-43d4-9b04-3a5a07f323bc
> [FEAT] 북마크 이동 시 토스트 알람 생성

- .github/workflows/baguni.test.client.deploy.yml
- frontend/techpick/src/app/(unsigned)/share/[uuid]/page.tsx
- frontend/techpick/src/app/layout.tsx
- 기능 :
- issue : #
- 기존의 문제가 있었던 도커 파일 환경변수명을 수정했습니다.
- 절대 경로로 OG image를 가져오게 변경했습니다.
> [FIX] 테스트 서버 배포 도커 파일 수정 및 OG image 가져올 때 환경변수 제거

- .github/workflows/baguni.test.client.deploy.yml
- frontend/techpick/src/app/(unsigned)/share/[uuid]/page.tsx
- frontend/techpick/src/app/layout.tsx
- 기능 :
- issue : #
현재 ogImage를 다음과 같이 가져오고 있어서 환경변수를 이용해 url을 변경했습니다.
```
<meta property="og:image" content="http://localhost:3000/image/og_image.png">
```
###
```
<meta property="og:image" content="http://{환경 서버의 값}/image/og_image.png">
```
> [FIX] OG Image를 가져오는 경로를 절대 경로로 수정

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiResponse.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- Close #909
- 기능 : 픽 중복 확인하는 API 구현
- issue : #909
- 기존에 deprecated 되었던 `/api/picks/link`를 리팩토링 하였습니다.
- 중복된 링크가 없으면 400 에러 발생시키던 로직에서 false를 반환하도록 변경하였습니다.
> [FEAT] 픽 중복 확인하는 API 구현

- frontend/techpick/src/components/Search2/FilterContainer.tsx
- frontend/techpick/src/components/Search2/FilterOptions.tsx
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- Close #925 
기능 :
esc 버튼을 누를 때, select 뿐만 아니라 다이얼로그까지 같이 닫히는 동작을 @sangwonsheep 님께서 알려주셨습니다.
해당 동작의 원인은 esc 버튼을 누를 때, 다이얼로그의 esc 까지 같이 동작하는 것이 원인이었고, select가 열려있으면 esc가 다이얼로그를 변경하지 못하게 수정해서 해결했습니다.
- issue : #925
> [FIX] 검색 창에서 태그 선택 후 esc 눌렀을 시 검색 창이 종료되는 문제 해결

- frontend/techpick/src/components/MyPage/myPageShareFolderField.css.ts
- frontend/techpick/src/hooks/useMyShareFolder.ts
- Close #926 
기능 :
폴더명이 짧을 때 버튼이 잘리는 경우가 있었습니다. 해당 문제는 그리드를 이용해 비율을 퍼센트로 나누는 것이 문제였습니다. (해당 버튼에게 주어진 width와 버튼의 width보다 작았을 때 발생했습니다.) 따라서 minWidth를 부여함으로써 해결했습니다.
- issue : #926
> [FIX] 길이가 짧은 폴더 공유 시 공유 취소 버튼이 짤리는 문제 수정

- frontend/techpick/src/components/FolderAndPickDndContextProvider.tsx
- frontend/techpick/src/utils/index.ts
- frontend/techpick/src/utils/pointerWithinWithClosestCenter.ts
- 기능 : 
- issue : #827 
드래그 앤 드랍 충돌 알고리즘을 변경했습니다.
이전의 `pointerWithin`은 마우스의 위치만 추적하느라, 아래의 gif처럼 쭉 아래로 땡겼을 때 아래로 정렬이 아닌 원래 자리로 돌아갔습니다.
그리고 `closestCenter`는  쭉 아래로 땡겼을 때 아래로 이동할 수 있었지만 북마크를 폴더로 이동할 수 없었습니다. 
따라서 drop이 가능한 영역에서는 `pointerWithin` 으로 세밀하게 조정이 되고 그렇지 않은 경우에는 `closestCenter`로 자연스러운 동작이 구현되게 하였습니다.
| ![before](https://github.com/user-attachments/assets/4393e15e-575c-4373-84fc-1c0d13cb2f1f) | ![after](https://github.com/user-attachments/assets/13c93811-dfb0-49e7-a4e0-37bc7550e369) |
> [FEAT] dnd 충돌 알고리즘 수정

- backend/baguni-api/src/main/resources/logback-spring.xml
- backend/baguni-batch/src/main/resources/logback-spring.xml
- backend/baguni-entity/build.gradle
- backend/baguni-entity/src/main/resources/application-entity.yaml
- backend/baguni-entity/src/main/resources/db/migration/V1__init_schema.sql
- backend/baguni-entity/src/main/resources/db/migration/V2__add_user_idToken.sql
- Close #912 
- 기능 : 
- flyway 추가
- 이제 local도 ddl-auto는 validate / none만 사용합니다.
- flyway가 을 `db.migration` 디렉토리에 있는 sql 스크립트를 버전대로 실행합니다.
- :card_file_box: `ddl-auto: update` 에 버전 관리가 추가된 느낌...? 
- 이제 모든 db 변경 사항은 sql 스크립트로 작성해야 합니다. 
- 추가 공유 :
- 이 PR이 도입되면, 운영 환경 DB에 따로 접속해서 업데이트 안해도 됨.
- 현재 DB 스키마랑 flyway 스키마랑 비교해서, 다른 부분만 순차적으로 적용함
- 참고 이미지  (`프로그램 시작할 때 실행되는 로그`)
- flyway가 mysql에 추가 생성한 테이블
- issue : #912 
위 baseline-on-migrate 옵션은 나중에 꺼야 할 것 같은데, 조금 더 찾아보겠습니다.
https://documentation.red-gate.com/fd/baseline-on-migrate-224919695.html
> [FEAT] flyway 도입

- frontend/techpick/src/components/PickRecord/SharePickRecord.tsx
- frontend/techpick/src/components/PickTagPicker/PickTagAutocompleteDialog.tsx
기능 :
해당 버그는 @sangwonsheep 님께서 보고해주셨습니다.
문제의 원인은 인풋의 값이 바뀔 때는 계속 생성될 수 있는지 값을 확인하지만 생성 혹은 선택을 할 때, 인풋의 값을 초기화하며 생성 여부를 파악하지 않았기 때문이었습니다. 
따라서 인풋의 값이 바뀌면서 생성 여부를 판단하는 함수도 동작하게 했기에 버그가 생기지 않습니다.
- issue : #849
> [FIX] 웹에서 태그 생성 후 빈 태그가 생성이 가능한 문제 해결

- backend/baguni-domain/src/main/java/baguni/domain/model/link/Link.java
- backend/baguni-domain/src/main/resources/db/migration/V3__add_link_timestamp.sql
- 참고 #954 
- 기존 데이터들은 해당 필드가 0으로 설정됩니다.
> [FIX] 링크에 수정 시간 필드 추가

- backend/baguni-common/build.gradle
- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqConfig.java
- backend/baguni-common/src/main/java/baguni/common/event/events/ErrorLogEvent.java
- backend/baguni-common/src/main/java/baguni/common/event/events/Event.java
- backend/baguni-common/src/main/java/baguni/common/event/listener/SlackNotificationEventListener.java
- backend/baguni-common/src/main/java/baguni/common/event/messenger/CrawlingEventMessenger.java
- backend/baguni-common/src/main/java/baguni/common/event/messenger/RankingEventMessenger.java
- backend/baguni-common/src/main/java/baguni/common/event/messenger/SlackNotificationEventMessenger.java
- backend/baguni-common/src/main/java/baguni/common/exception/base/ApiExceptionHandler.java
- backend/baguni-common/src/main/java/baguni/common/util/ErrorLogEventBuilder.java
- backend/baguni-common/src/main/java/baguni/common/util/SlackNotificationService.java
- backend/baguni-common/src/main/resources/application-common.yaml
- Close #961
- 기능 : 서버 에러 발생 시 슬랙 알림 기능 구현
- issue : #961
#928 에서 개선하기로 한 Exchange 1개에 routing key 방식으로 변경
routing key에 맞게 queue 설정
- "ranking" -> ranking queue
- "crawling" -> crawling queue
- "slack" -> slack notification queue
RabbitmqConfig 참고 부탁드립니다.
슬랙 API 라이브러리가 존재하여 사용하였습니다.
`implementation 'com.slack.api:slack-api-client:1.45.1'`
- 로그 발생하는 부분과 슬랙 알림은 비동기로 분리하여 슬랙 알림은 메세지 큐에서 처리하도록 하였습니다.
이유 : 로그 발생과 슬랙 알림 작업은 분리가 필요하다고 생각했습니다. 슬랙 관련 문제가 발생하면 리트라이나 실패 시 메세지 큐에서 처리할 수 있게 하여 정상 동작하도록 할 수 있을 것이라 생각했습니다.
- 슬랙 알림 flow
1. Exception, ApiException(`FatalErrorLevel`) 발생 
2. SlackNotificationService에서 Event 전달
3. SlackNotificationEventMessenger에서 메세지 큐 Exchange에 메세지 발행
4. SlackNotificationEventListener에서 메세지를 꺼내 webhook url로 post 요청하여 슬랙에 알림 전송
추가하고 싶은 내용이 있거나 메세지 순서를 바꾸고 싶으면 말씀해주세요! …
> [FEAT] 서버 에러 발생 시 슬랙 알림 기능 구현

- frontend/techpick/src/app/(signed)/recommend/page.tsx
- frontend/techpick/src/components/FolderAndPickDndContextProvider.tsx
- frontend/techpick/src/styles/dialogStyle.css.ts
- #990 
해당 문제의 원인은 dnd를 막는 컴포넌트를 잘 못 배치했기에 발생한 문제였습니다. 수정했습니다.
- #988 
해당 문제의 원인은 모바일 뷰에서 적용되는 스타일이 데스크탑에서도 적용됐기에 발생한 문제였습니다. 수정했습니다.
- 북마크 dnd 로직 변경
추천 페이지에서만 dnd 충돌 알고리즘을 달리 적용했습니다.
> [FIX] 홈 화면 배경색 짤림 수정, 다이얼로그 망가진 것 수정, 추천 북마크 dnd 로직 변경

- backend/baguni-common/src/main/java/baguni/common/config/OpenGraphConfig.java
- backend/baguni-common/src/main/java/baguni/common/lib/opengraph/OpenGraphReaderSelenium.java
- Close #1005
- 기능 : Selenium Timeout 관련 문제
- issue : #1005
- Selenium 타임 아웃 10초 -> 2분으로 설정
- TimeoutException 발생 시 로그 찍도록 설정 (이후 Jsoup 사용할 수 있게 주석 추가)
```java
catch (org.openqa.selenium.TimeoutException e) {
result = new OpenGraphReaderJsoup(openGraphOption).read(uri); 
}
```
이 방식대로 jsoup 사용했을 때 image_url 제대로 가져오는 것을 확인했습니다.
> [BUG] Selenium Timeout 관련 문제

- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqConfig.java
- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqCustomErrorHandler.java
- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqErrorHandlerConfig.java
- Close #1016
- 기능 : RabbitMQ 순환 참조 문제 해결
- issue : #1016
- `RabbitmqCustomErrorHandler`의 `@Lazy`, `@Component` 제거
- `RabbitmqErrorHandlerConfig` `@Configuration`에서 `RabbitmqCustomErrorHandler` 수동 빈으로 등록
- `RabbitmqConfig`의 `rabbitListenerContainerFactory` 메서드에서 파라미터로 받도록 변경
```java
@Bean
public SimpleRabbitListenerContainerFactory rabbitListenerContainerFactory(
CachingConnectionFactory cachingConnectionFactory,
RabbitmqCustomErrorHandler rabbitmqCustomErrorHandler // 추가된 부분
) {
```
이렇게 해서 순환 참조 문제 해결
- 기존 : RabbitConfig -> RabbitmqCustomErrorHandler -> EventMessenger -> RabbitTemplate (RabbitConfig) -> RabbitmqCustomErrorHandler -> ... 순환 구조
- 변경 : RabbitmqCustomErrorHandler -> EventMessenger -> RabbitTemplate (RabbitConfig) 순환 구조 끊김
RabbitConfig에서 RabbitmqCustomErrorHandler를 생성자 주입하면서 …
> [BUG] 순환 참조 문제 해결

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/sharedFolder/controller/SharedFolderApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/tag/controller/TagApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/tag/dto/TagApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-api/src/test/java/baguni/api/application/folder/controller/FolderApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/application/folder/controller/FolderApiControllerUnitTest.java
- backend/baguni-api/src/test/java/baguni/api/application/pick/controller/PickApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/application/pick/controller/PickApiControllerUnitTest.java
- backend/baguni-api/src/test/java/baguni/api/application/sharedFolder/controller/SharedFolderApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/application/sharedFolder/controller/SharedFolderApiControllerUnitTest.java
- backend/baguni-api/src/test/java/baguni/api/application/suggestion/controller/RankingApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/application/tag/controller/TagApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/application/tag/controller/TagApiControllerUnitTest.java
- backend/baguni-api/src/test/java/baguni/api/application/user/controller/UserApiControllerTest.java
- backend/baguni-api/src/test/java/baguni/api/service/pick/service/PickServiceTest.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickCommand.java
- Close #892
- 기능 : 컨트롤러 테스트 구현
- issue : #892
- API 모듈의 라인 커버리지 74%, 분기 커버리지 65% 달성
- 링크 API, 이벤트 API 제외하고 모든 API 테스트 완료
- 다음 작업을 위해 테스트 코드 작성은 멈추고 리팩토링이 진행될 때 수정하는 방향으로 가면 좋을 것 같습니다.
- API 폴더만 보면, 라인 커버리지 92%, 분기 커버리지 94% 입니다.
- Batch 모듈, Ranking 모듈 테스트 코드 작성 필요
> [FEAT] Controller 테스트 구현

- backend/baguni-api/src/main/java/baguni/api/application/extension/controller/ExtensionApiControllerV1.java
- backend/baguni-api/src/main/java/baguni/api/application/extension/dto/ExtensionApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/extension/dto/ExtensionApiRequest.java
- backend/baguni-api/src/main/java/baguni/api/application/extension/dto/ExtensionApiResponse.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickTagRepository.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickCommand.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickMapper.java
- 기능 : 익스텐션 픽 저장 API, 휴지통 비우기 API
- issue : #1000, #999
- 픽 저장 시 태그 설정, 폴더 설정이 가능하도록 하였습니다.
- 익스텐션 전용 컨트롤러, Mapper, DTO를 분리하였습니다. (픽 저장만)
- 휴지통 API 구현
- 현재 미분류로 픽 저장하는 부분은 모든 유저가 버전 업 되어 사용하지 않을 때 삭제하겠습니다.
1. 익스텐션에서는 저장만 가능하게 하고, 수정 폼은 보여주지 않을 계획인가요? 
(저는 중복 저장을 하려면 저장 폼만 보여줘야 한다고 생각합니다. + 누르면 익스텐션이 닫히기 때문)
2. 익스텐션 전용 API가 저장 외에 다른 API가 필요할까요?
(내 폴더 리스트 조회, 태그 리스트 조회, 존재하는 픽 조회)
익스텐션에서 리스트 조회하는 부분이 수정되거나 필요한 API가 있을 때 추가하는 방향은 어떨까요?
> [FEAT] 익스텐션 픽 저장 API, 휴지통 비우기 API

- backend/baguni-api/src/main/java/baguni/api/application/mobile/controller/MobileApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/service/folder/service/FolderService.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/folder/FolderDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/folder/FolderQuery.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/folder/FolderRepository.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickQuery.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickCommand.java
- 기능 : 모바일 뷰 폴더 리스트, 픽 페이지네이션 API
- issue : #1031, #1032
- 루트, 미분류, 휴지통 폴더 조회 jpql -> querydsl로 리팩토링
- 모바일에서 보여줄 폴더 리스트 API 구현
(미분류, 휴지통, 루트 하위 폴더 리스트 순)
- 픽 페이지네이션 API 구현
(폴더의 자식 픽 리스트를 DB에서 limit으로 잘라서 가져올 수 없는 문제 -> 전체 리스트 가져온 후 subList 이용)
(이후 관계 테이블 이용해서 리스트의 순서 보장해야 함)
querydsl을 사용하면서 관계 테이블 없이 데이터를 잘라서 가져올 수 없다는 것을 깨달음.
순서 리스트 리팩토링 들어가게 되면, 관계 테이블 도입해서 간격을 두는 방식은 어떤지?
리스트 : [40, 30, 11, 55, 32, 19, 33, 101, 3, 22, 88] 
1. 초기에 각 아이템에 sequence를 **10씩** 띄워 할당
- 40 (sequence=10), 30 (sequence=20), 11 (sequence=30)
2. **맨 앞**에 새 아이템을 삽입할 때는, **기존 첫 아이템 seqence(10)보다 작은 값**(10/2 = 5)을 할당
3. 중간에 삽입할 때는 **“앞 아이템 seq”와 “뒤 아이템 seq”의 중간값**을 할당
- 40 (sequence=10)과 30 (sequence=20) 사이에 삽입 -> ((20+10) / 2 = 15)
맨 앞에 계속 삽입하게 되면, 점점 더 작은 숫자(5 → 3 → 2 → 1 → 0 → -1 → …)가 되어버릴 수 있음.
중간 삽입도 앞 seq=20, …
> [FEAT] 모바일 뷰 폴더 리스트, 픽 페이지네이션 API

- frontend/techpick/src/app/(signed)/folders/[folderId]/layout.tsx
- frontend/techpick/src/app/(signed)/folders/page.tsx
- frontend/techpick/src/constants/route.ts
SSR을 적용하면서 `folders/[folderId]` url일 때, folderId가 숫자가 아닌 문자(ex. unclassified, recycle-bin)로 접근하게 된다면 문제가 발생했습니다. 따라서 검증 로직을 추가하여 숫자일 때만 요청을 보내고, 그렇지 않을 때에는 리다이렉트 되게 변경했습니다.
- 기능 :
- #1036 
- #1020
> [FIX] /folders/unclassified로 접속 시에 홈으로 리다이렉트

- backend/baguni-api/src/main/java/baguni/security/handler/BaguniApiAuthExceptionEntrypoint.java
- Close #1046 
- issue : #1046 
- 내용
- warning으로 낮추지 않고, **아예 로그를 삭제함.**
- 이유: 
1. 관련 Response 에러 레벨이 `can-happen` (발생하는게 정상적 상황) 이다. 
2. 이 예외는 식별되지 않은 사용자도 포함되기 때문에 (`eg. 토큰이 없어서 식별이 안된경우`)
로그에서 특정 사용자에게 자주 발생한다~ 이런 정보를 얻기 어렵다.
- 결론:
- 로그를 남김의 의미가 없다고 판단, 삭제함.
> [FIX] 토큰 만료 관련 로그 제거

- backend/baguni-api/src/main/resources/logback-spring.xml
- backend/baguni-batch/src/main/resources/logback-spring.xml
- backend/baguni-common/build.gradle
- backend/baguni-common/src/main/resources/application-common.yaml
- backend/baguni-ranking/src/main/resources/logback-spring.xml
- backend/build.gradle
- Close #1048 
- 기능 : 로그백을 OpenTelemety 로그 포맷으로 변경했습니다.
그 과정에서, SQL 부분은 콘솔에만 찍히도록 변경했는데
왜냐면 OpenTelemetry + LGTM 스택으로 가면서 Trace에 자동으로 SQL문이 포함되서 기록되기 때문에
로그파일로 저장할 필요가 없어졌습니다.
(굳이 로그백으로 찍지 않아도 된다는 말)
- 참고 : LGTM 설정이 마무리 되어 SQL문이 실행 시간과 함께 자동 측정됩니다. 
개발 / 운영 서버에 반영해야 하기에 상세 사항은 수요일에 만나서 공유 드릴께요!
- 토의 필요 :
:warning: 히카리CP 풀 로그가 자주 / 많이 찍혀서 로그 보기 어렵습니다.
이건 로그로 남기지 않고 Prometeus로 Metric 수집하는 식으로 변경하려 합니다.
의견 주세요!
- Request별 각 실행 소요 시간 및 SQL 쿼리 측정
- Trace 별로 보기
- issue : #1048
> [CHORE] OpenTelemetry 로그 형식으로 로그백 수정 (콘솔은 유지)

- frontend/techpick/src/components/ScreenLogger.tsx
현재 봇들이 방문하는 경우가 이벤트에 찍히는데 봇이 아닌 경우에만 이벤트를 생성하도록 변경했습니다.
- 기능 :
- issue : #
> [FEAT] 봇이 아닐 때만 방문 log 찍기

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiResponse.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickMapper.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/dto/PickResult.java
- Close #1065 
- 수정 :  `픽 조회 API`에서 랭킹 데이터 제거 (`isHot`, `viewCount` 필드 제거)
- issue : #1065 
1. :warning: 해당 부분 제거된 이후 성능 재측정 해볼 예정
2. :warning: 미사용 DTO 필드 삭제하면서 테스트 코드도 변경 필요 (`제가 다음 PR에서 진행하겠습니다`)
> [FIX] Pick 조회 API에서 조회수 데이터 제거

- frontend/techpick/src/app/(signed)/layout.css.ts
- frontend/techpick/src/app/(signed)/layout.tsx
- frontend/techpick/src/app/layout.tsx
- frontend/techpick/src/providers/ThemeProvider.tsx
- frontend/techpick/src/providers/themeProvider.css.ts
웹에서 제공하는 pull to refresh와 브라우저에서 제공해주는 pull to refresh가 동시에 동작합니다. 이를 수정합니다.
참고자료 - [크롬 브라우저 블로그](https://developer.chrome.com/blog/overscroll-behavior?hl=ko)
- 기능 :
- issue : #
> [FIX] 모바일 화면 default pull to refresh 차단 

- frontend/techpick/src/components/MobileEmptyPickRecordImage.tsx
- frontend/techpick/src/components/mobileEmptyPickRecordImage.css.ts
- Close #1086
- issue : #1086
https://github.com/user-attachments/assets/d4d7c6dd-242b-4e0c-8f5a-e8b2fc24eecb
> [FIX] 모바일 화면에서 픽이 없을 때, 이미지 크기 축소

- frontend/techpick-extension/src/chrome-extension/manifest.json
- frontend/techpick-extension/src/components/CreatePickForm.tsx
- frontend/techpick-extension/src/pages/BookmarkPage.tsx
- Close #1060 
- #1060 
이전에는 아이콘을 클릭하자마자 바로 미분류로 추가되었기에 동시에 아이콘이 변경되었지만, 
현재는 버튼을 눌러야만 북마크가 추가됩니다. 따라서 북마크 버튼을 누를 때, 아이콘이 바뀌도록 변경되었습니다.
> [FIX] 익스텐션 북마크 추가할 때 아이콘 변경하기

- frontend/techpick/src/app/(unsigned)/share/[uuid]/opengraph-image.tsx
- frontend/techpick/src/app/(unsigned)/share/[uuid]/page.tsx
- issue : #1077
local에서 테스트할 수 없어서 개발 서버에 배포된 후에 테스트 진행해보겠습니다.
> [FIX] og image 출력방식 변경

- frontend/techpick/src/app/api/generate-og-image/route.tsx
- Close #1103 
- #1103 
이렇게 비어있는 이미지가 만들어졌었는데 로직에서 문제점이 있었습니다. 이를 수정했습니다.
> [FIX] og image 생성 로직 변경

- frontend/techpick/src/components/FolderContentHeader/CurrentFolderNameSection.tsx
- frontend/techpick/src/components/FolderContentHeader/FolderContentHeader.tsx
- frontend/techpick/src/components/FolderContentHeader/currentFolderNameSection.css.ts
- frontend/techpick/src/components/FolderContentHeader/folderContentHeader.css.ts
- frontend/techpick/src/constants/route.ts
- Close #1027 
- #1027 
공유중인 폴더라면 아래의 `공유 중` 버튼을 눌러 공유 폴더로 이동할 수 있습니다.
이전까지의 마이페이지에서 이동하여 공유 폴더를 찾아야하는 번거로운 과정을 생략할 수 있습니다.
> [FEAT] 공유 중 버튼을 누르면 공유 폴더 페이지로 이동

- backend/baguni-common/src/main/java/baguni/common/exception/level/NormalErrorLevel.java
- Close #1109 
- 기능 : 정상 예외 처리임에도 Error 레벨 로그가 남는 버그 수정
- issue : #1109 
`log.error`를 `log.info`로 변경
> [FIX] Normal 로그 레벨 수정

- backend/baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkUpdateEventListener.java
- backend/baguni-ranking/src/main/java/baguni/ranking/infra/RankingEventListener.java
- 기능 : 메시지 소비 관련 로그 통일
- 랭킹 서버와 배치 서버의 로그를 통일 + url을 로그에서 출력하도록 수정
위 이미지를 보면 각 소비 메시지가 다르고, url이 출력되지 않음. 이 부분 통일함.
> [REFACTOR] 메시지 소비 로그 메시지 변경

- backend/baguni-common/src/main/java/baguni/common/exception/level/ErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/FatalErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/NormalErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/WarningErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/util/CachedHttpServletRequest.java
- backend/baguni-common/src/main/java/baguni/common/util/RequestLoggingFilter.java
- Close #1116
1. 그라파나 에러 알림 작업이 끝남에 따라 
에러 레벨을 다시 원상복구합니다.
2. 토의 후 삭제될 부분에 대해 주석을 남겼고, 
Request 시작시 해당 정보를 기록하는 로그를 추가했습니다.
> [FIX] 에러 로그 메시지 레벨 복구

- frontend/techpick/sentry.client.config.ts
- frontend/techpick/sentry.edge.config.ts
- frontend/techpick/sentry.server.config.ts
- frontend/techpick/src/apis/apiClient.ts
- Close #1051 
- #1051 
이제 로컬 개발 환경에서 발생하는 에러는 송신하지 않습니다.
또한 모든 에러가 아닌 예측하지 못한 에러와, 500번 서버 에러만 발생됩니다.
> [FEAT] 센트리 개발 환경에서는 에러 전송하지 않게 변경

- frontend/techpick/src/app/(unsigned)/share/[uuid]/MobileSharedPickRecord.tsx
> [FIX] 공유 폴더 모바일 화면 모두 보이는 문제 수정

- backend/baguni-batch/src/main/java/baguni/batch/listener/LinkRankingEventListener.java
- backend/baguni-batch/src/main/java/baguni/batch/listener/LinkUpdateEventListener.java
- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqConfig.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkStatsRepository.java
- backend/baguni-domain/src/main/java/baguni/domain/model/link/LinkStats.java
- backend/baguni-domain/src/main/resources/db/migration/V4.6__add_link_statistic_table.sql
- Close #1143 
이 PR은 #1143 의 일부 작업입니다.
PR 반영시 배치서버도 집계하고, 랭킹 서버도 집계합니다. 
- 기능 : 배치 서버에 랭킹 집계 기능 추가 
- issue : #1143
기존 기능을 유지하면서, 배치에 집계 기능만 추가했습니다.
테스트 완료되기 전까진 기존 랭킹 큐를 유지할 예정입니다.
0. 작업 이전 일부 리팩토링 --> :heavy_check_mark:  `완료`
1. A - 기존 랭킹 서버를 유지하면서 Batch에 동일한 랭킹 집계 기능 구현 -->  :heavy_check_mark:  :ping_pong: `지금 pr`
1. B - 서버 반영 전에 mongo 데이터를 mysql로 이전  :heavy_check_mark:  :ping_pong: `지금 pr`
2.  랭킹 정보 획득 api 추가
3. 테스트 완료 후 랭킹 서버 + rest client + 관련 큐 삭제
4. 서버 2개로 줄이기가 끝나면 staging 브랜치 추가 
:warning: 이후 작업 및 테스트가 완료되었을 때 랭킹 서버를 완전히 삭제하겠습니다.
> [FEAT] 배치 서버에 랭킹 집계 기능 추가

- backend/baguni-api/src/main/java/baguni/api/application/suggestion/controller/RankingApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/dto/RankingResponse.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-api/src/main/java/baguni/api/service/ranking/dto/RankingResult.java
- backend/baguni-api/src/main/java/baguni/api/service/ranking/service/RankingService.java
- backend/baguni-api/src/main/java/baguni/api/service/user/service/strategy/RankingInitStrategy.java
- backend/baguni-common/src/main/java/baguni/common/lib/cache/CacheType.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkStatsRepository.java
- Close #1143 
이 PR은 #1143 의 일부 작업입니다.
- 기능 : 랭킹 api 구현 인프라를 mysql로 수정
- issue : #1143
> [FEAT] 랭킹 api 교체 작업
