- .github/workflows/backend_pr_bot.yml
- Close #5
- 기능 : backend pr 빌드봇 추가
- issue : #5
> [FEAT] 백엔드 pr 빌드봇 추가

- backend/build.gradle
- backend/src/main/java/kernel360/techpick/config/SwaggerConfig.java
- Close #8 
- 기능 : Swagger 설정 추가
- issue : #8 
- Swagger(Springdoc) 의존성 추가
- SwaggerConfig 추가
- 최소한의 설정만 추가
- 추후 Spring Security 도입 후 인증 관련 설정 추가 예정
- 참고 : https://www.notion.so/Swagger-35ebb101f6dc44638e61d9d7ff72f3f6
> feat: swagger 설정 추가

- backend/src/main/java/kernel360/techpick/core/exception/base/ApiErrorCode.java
- backend/src/main/java/kernel360/techpick/core/exception/base/internal/ApiErrorBody.java
- backend/src/main/java/kernel360/techpick/core/exception/base/internal/ApiErrorResponse.java
- backend/src/main/java/kernel360/techpick/core/exception/base/internal/ApiException.java
- backend/src/main/java/kernel360/techpick/core/exception/base/internal/ApiExceptionHandler.java
- backend/src/main/java/kernel360/techpick/core/exception/feature/tag/ApiTagException.java
- backend/src/main/java/kernel360/techpick/core/exception/feature/user/ApiUserException.java
- backend/src/main/java/kernel360/techpick/core/model/common/TimeTracking.java
- backend/src/main/java/kernel360/techpick/core/model/event/LinkViewEvent.java
- backend/src/main/java/kernel360/techpick/core/model/link/Link.java
- backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
- backend/src/main/java/kernel360/techpick/core/model/pick/PickTag.java
- backend/src/main/java/kernel360/techpick/core/model/rss/RssRawData.java
- backend/src/main/java/kernel360/techpick/core/model/rss/RssSupportingBlog.java
- backend/src/main/java/kernel360/techpick/core/model/tag/Tag.java
- backend/src/main/java/kernel360/techpick/core/model/user/AgeGroup.java
- backend/src/main/java/kernel360/techpick/core/model/user/JobGroup.java
- backend/src/main/java/kernel360/techpick/core/model/user/Role.java
- backend/src/main/java/kernel360/techpick/core/model/user/SocialType.java
- backend/src/main/java/kernel360/techpick/core/model/user/User.java
- backend/src/main/java/kernel360/techpick/feature/tag/controller/TagApiV1.java
- backend/src/main/java/kernel360/techpick/feature/tag/controller/TagPrivateController.java
- backend/src/main/java/kernel360/techpick/feature/tag/controller/TagPrivateControllerV1.java
- backend/src/main/java/kernel360/techpick/feature/tag/exception/TagCustomException.java
- backend/src/main/java/kernel360/techpick/feature/tag/model/dto/TagCreateRequest.java
- backend/src/main/java/kernel360/techpick/feature/tag/model/dto/TagCreateResponse.java
- backend/src/main/java/kernel360/techpick/feature/tag/repository/TagRepository.java
- backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
- backend/src/main/java/kernel360/techpick/feature/tag/util/TagConverter.java
- Close #42 
- 기능 : 디렉토리 구조 잡기 + 공통 Exception 처리
- issue : #42 
- :bookmark_tabs: [**팀 예외 처리 방식**](https://github.com/Kernel360/F2-TECHPICK/wiki/API-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)  - 위키 참고
예외 처리 방식은 팀 WIKI 에 정리해두었으니 참고해주세요.
+) 오늘 회의한 내용 사진
> feat: 디렉토리 구조 및 공통 예외처리 설정

- .github/workflows/test-server-deploy.yml
> feat: 배포 테스트

- .github/workflows/test-server-deploy.yml
> deploy test

- .github/workflows/test-server-deploy.yml
- backend/Dockerfile
- backend/docker-compose.yaml
- backend/src/main/resources/logback-spring.xml
- Close #54 
- 기능 : 이제부터 backend 브랜치에 머지되면, 테스트 서버로 배포가 진행됩니다.
- issue : #54 
- crud 구현 상황에 맞춰서 프론트 분들이 작업하실 수 있게 준비하겠습니다.
> feat: 테스트 api 서버 배포

- backend/src/main/java/kernel360/techpick/core/model/pick/PickTag.java
- Close #72
- 기능  :PickTag 엔티티 변경
- issue : #72
1. User 필드 삭제
- Pick 에서 확인 가능
- PickTag 엔티티에서 User로 조회하는 경우가 없음
2. Pick 필드 추가
- 설계대로면 들어가있어야하는데 누락되어있었음
> [refactor] PickTag 엔티티 변경

- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
close #96
- 기능 : 로그인 페이지 허용 uri 변경
- issue : #96
`.requestMatchers("/api/login/**").permitAll()`
> [fix] 로그인 페이지 허용 uri 변경

- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
close #96
- 기능 : 로그인 uri 접근 허용
- issue : #96 
`.requestMatchers("/api/login/**").permitAll()`
> [hot fix]: 로그인 uri 접근 허용

- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
- backend/src/main/resources/application.yaml
close #101
- 기능 : Spring Security CORS 설정 추가
- issue : #
Spring Security CORS 설정 추가
> [refactor] Spring Security CORS 설정 추가

- backend/src/main/java/kernel360/techpick/core/config/SchedulingConfig.java
- Close #109 
- 기능 : 스케줄러 설정 추가
- issue : #109 
배포 서버에 스케줄러가 동작하지 않는 문제 발생
로컬에서 확인 결과 로컬에서도 돌아가지 않았음.
놓친 설정 찾아서 추가.
`SchedulingConfig`에 `@EnableScheduling` 추가
> refactor: 스케줄러 설정 추가

- backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
- backend/src/main/java/kernel360/techpick/core/model/folder/FolderType.java
- backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
- backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderException.java
close #108 
- 기능 : 폴더 기본설계
- issue : #108 
- Folder Entity 구현
- Folder Exception, ErrorCode 구현
- Pick에 `Folder parent` 컬럼 추가 필요
> [feat] Folder 기본 설계

- backend/src/main/java/kernel360/techpick/core/model/folder/FolderStructure.java
- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderStructureProvider.java
- backend/src/main/java/kernel360/techpick/feature/folder/repository/FolderStructureRepository.java
- Close #112
- 기능 : FolderStructure 설계
- issue : #112
- 폴더구조는 각 유저당 유일하게 존재.
- 회원가입시 자동으로 생성
- 폴더구조는 String으로 표현되며, 폴더구조와 순서가 저장된 json을 String으로 저장
> [feat] FolderStructure 설계

- backend/src/main/java/kernel360/techpick/core/auth/handler/OAuth2SuccessHandler.java
- Close #128 
- 기능 : 프론트 로그인 로컬 테스트를 위한 redirect url 설정
- issue : #128
로그인 성공 후 다음 url로 리다이렉트
`http://localhost:3000/login/ok`
프론트 배포 이후 url 수정 예정
> [FEAT] 프론트 로그인 로컬 테스트를 위한 redirect url 설정

- backend/src/main/java/kernel360/techpick/core/auth/handler/OAuth2SuccessHandler.java
- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
- Close #134
- 기능 : 프론트 로컬 테스트를 위한 설정
- issue : #134 
프론트 로컬 테스트 도메인
`https://local.minlife.me:3000`
> [REFACTOR] 프론트 로컬 테스트를 위한 설정

- backend/src/main/java/kernel360/techpick/core/auth/Filter/TokenAuthenticationFilter.java
- backend/src/main/java/kernel360/techpick/core/util/CookieUtil.java
- Close #153
- 기능 :로그인 쿠키 버그 수정
- issue : #153
로그인쿠키가 `access_token`을 덮어쓰는 버그 수정
> [HOTFIX] 로그인 쿠키 버그 수정

- backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickController.java
- backend/src/main/java/kernel360/techpick/feature/pick/model/PickProvider.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickStructureService.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickIdDto.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/dto/PickMoveDto.java
- backend/src/main/java/kernel360/techpick/feature/pick/validator/PickValidator.java
- Close #123 
- 기능 : Structure와 연관된 Pick Service 구현
- issue : #123 
- PickService 분리
- PickController에서 사용하는 메서드를 PickService로 분리
- StructureController에서 사용하는 메서드를 PickStructureService로 분리
- PickStructureService 구현
- PickService 설계
- PickService, PickController 구현 예정
바로 확인 부탁드립니다! Pick 작업 바로 진행하겠습니다!
> [FEAT] Structure와 연관된 Pick Service 구현

- backend/src/main/java/kernel360/techpick/feature/folder/model/FolderProvider.java
- backend/src/main/java/kernel360/techpick/feature/folder/repository/FolderRepository.java
- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderStructureService.java
- backend/src/main/java/kernel360/techpick/feature/pick/model/PickProvider.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickStructureService.java
- backend/src/main/java/kernel360/techpick/feature/structure/service/StructureService.java
- backend/src/main/java/kernel360/techpick/feature/structure/service/dto/StructureDeleteRequest.java
- backend/src/main/java/kernel360/techpick/feature/structure/service/dto/StructureMoveRequest.java
- backend/src/main/java/kernel360/techpick/feature/structure/validator/StructureValidator.java
- Close #165 
- 기능 : Structure Validator 구현
- issue : #165
Structure Validator 구현
- client에서 보낸 json의 노드 개수가 db와 동일한지 검증
- client에서 보낸 json의 노드 부모관계가 db와 동일한지 검증
> [FEAT] Structure Validator 구현

- backend/src/main/java/kernel360/techpick/core/config/SwaggerConfig.java
- Close #172
- 기능 : swagger 쿠키 설정 수정
- issue : #172
swagger 쿠키 설정 수정.. 설정 생성후 적용 안한것을 적용...
> [HOTFIX] swagger 쿠키 설정 수정

- backend/src/main/java/kernel360/techpick/core/model/tag/Tag.java
- backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
- backend/src/main/java/kernel360/techpick/feature/tag/model/TagMapper.java
- backend/src/main/java/kernel360/techpick/feature/tag/service/dto/TagCreateRequest.java
- backend/src/main/java/kernel360/techpick/feature/tag/service/dto/TagResponse.java
- backend/src/main/java/kernel360/techpick/feature/tag/service/dto/TagUpdateRequest.java
- Close #183 
- 기능 : 태그 색상 번호 `colorNumber` 필드 추가
- issue : #183
> [FEAT] 태그 색상번호 데이터 추가

- backend/src/main/java/kernel360/techpick/core/auth/handler/OAuth2SuccessHandler.java
- backend/src/main/java/kernel360/techpick/core/config/SecurityConfig.java
- Close #198 
- 기능 : 시큐리티에 프론트엔드 도메인 추가
- issue : #198
> [FEAT] 프론트엔드 서버 도메인 추가

- .github/workflows/test-client-deploy.yml
- frontend/Dockerfile
- Close #200 
- 기능 : 프론트엔드 브랜치 병합시 --> 자동 배포되도록 스크립트 작성
- issue : #200
> [CI] 프론트엔드 서버 배포 스크립트

- frontend/techpick-extension/src/entities/tag/model/tagStore.ts
- frontend/techpick-extension/src/widgets/TagPicker/TagInfoEditPopoverButton/index.tsx
- Close #214 
- 기능 :
- issue : #214 
잘못된 변수 접근으로 인한 런타임 에러를 해결했습니다.
> [FIX] 런타임 에러 해결(잘못된 변수 접근)

- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickApi.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickController.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- Close #217 
- 기능 : Pick Url 조회시 Path Variable 문제, 픽 중복 생성 방지
- issue : #217
- Url을 Query Param으로 받도록 변경.
- 픽 중복 생성 방지
> [REFACTOR] Pick Url 조회시 Path Variable 문제, 픽 중복 생성 방지

- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickApi.java
- backend/src/main/java/kernel360/techpick/feature/pick/controller/PickController.java
- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
- Close #217 
- 기능 : Pick 생성 시 존재하지 않는 픽 조회하여 예외 터지는 문제 해결
- issue : #217 
Pick 생성 시 존재하지 않는 픽 조회하여 예외 터지는 문제 해결
> [HOTFIX] Pick 생성 시 존재하지 않는 픽 조회하여 예외 터지는 문제 해결

- backend/src/main/java/kernel360/techpick/feature/pick/service/PickService.java
hot 픽스 입니다.  Pick 중복 확인 로직 제거했습니다.
> [HOTFIX] Pick 중복 확인 로직 제거

- backend/src/main/java/kernel360/techpick/feature/structure/validator/StructureValidator.java
- Close #222 
- 기능 : 프론트엔드 디버깅용 log 출력 추가
- issue : #222
> [FEAT] 프론트엔드 디버깅용 로그 출력 추가

- backend/src/main/java/kernel360/techpick/feature/pick/service/PickStructureService.java
- backend/src/main/java/kernel360/techpick/feature/structure/model/StructureDataProxy.java
- backend/src/main/java/kernel360/techpick/feature/structure/validator/StructureValidator.java
노드 개수 비교를 unclassified 에 있는 픽을 포함해서 비교하는 오류 수정
- issue : #225
> [FIX] Structure Validator 버그 수정

- backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> test: 쓰레드 테스트 (synchronized)

- backend/data/schema.sql
- backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
- backend/src/main/resources/application.yaml
- Close #239 
- 기능 : Folder 복합 unique 제약 조건 추가 및 ddl 설정
- issue : #239
> [FIX] Folder 복합 unique 제약 조건 추가 및 ddl 설정

- frontend/techpick/src/app/login/page.tsx
- Close #259
- 기능 :
- issue : #259 
- 이제 로그인 이후 mainpage로 redirect됩니다.
> [FIX] 로그인된 상태일 때 메인 페이지로 리다이렉트

- backend/src/main/java/kernel360/techpick/feature/api/folder/controller/FolderApiSpecification.java
- backend/src/main/java/kernel360/techpick/feature/api/pick/controller/PickApiSpecification.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/controller/TagApiSpecification.java
- Close #263 
- 기능 : 구현해야 할 api 명세 작업
- issue : #263
> [CHORE] API 명세

- frontend/techpick/src/entities/pick/ui/PickCard.tsx
- frontend/techpick/src/entities/pick/ui/pickCard.css.ts
- frontend/techpick/src/widgets/TagPicker/TagAutocompleteDialog/index.tsx
- frontend/techpick/src/widgets/TagPicker/TagInfoEditPopoverButton/index.tsx
- frontend/techpick/src/widgets/TagPicker/index.tsx
- Close #267 
- 기능 :
- issue : #267 
1. 로딩 화면 시 스켈레톤 적용.
2. imageUrl이 없을 경우 빈 이미지 카드 생성.
3. 링크 적용 후 태그 픽커 버그 수정 (수정이나 삭제 동작 확인)
> feat: skelton 적용

- frontend/techpick/src/widgets/TagPicker/TagAutocompleteDialog/index.tsx
- Close #269
- 기능 :
- issue : #269 
- #269 의 비정상 동작이 정상동작 합니다.
> [FIX] 태그 생성 후 창 유지후에 수정 했을 때, 생성한게 추가가 안되는 로직

- backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
- backend/src/main/java/kernel360/techpick/feature/domain/pick/service/PickServiceImpl.java
- Close #279 
- 기능 : 체이닝으로 인한 가독성 저하 해결
- issue : #279
> [REFACTOR] pick service 코드에서 chaining 제거

- backend/src/main/java/kernel360/techpick/core/model/pick/PickTagRepository.java
- backend/src/main/java/kernel360/techpick/core/model/tag/Tag.java
- backend/src/main/java/kernel360/techpick/core/model/tag/TagRepository.java
- backend/src/main/java/kernel360/techpick/core/model/user/User.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiMapper.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiRequest.java
- backend/src/main/java/kernel360/techpick/feature/api/tag/dto/TagApiResponse.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/dto/TagCommand.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/dto/TagMapper.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/dto/TagResult.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/service/TagService.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/service/TagServiceImpl.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/pick/writer/PickWriter.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/pick/writer/PickWriterImpl.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/tag/reader/TagReader.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/tag/reader/TagReaderImpl.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/tag/writer/TagWriter.java
- backend/src/main/java/kernel360/techpick/feature/infrastructure/tag/writer/TagWriterImpl.java
- Close #271 
- 기능 : Tag v2 Service 구현
- issue : #271 
- 태그 v2 기능 구현
> [FEAT] Tag v2 Service 구현

- backend/src/main/java/kernel360/techpick/feature/infrastructure/pick/writer/PickWriterImpl.java
- Close #289 
- 기능 : 백엔드 PickWriter 예외 코드 미반영 수정
- issue : #289
>  fix: Pick Write 예외 처리 추가 (권한)

- frontend/techpick/src/components/DirectoryTreeSection/DirectoryTreeSection.css.ts
- Close #312 
- 기능 :
- issue : #312 
- [reshape](https://reshaped.so/docs/tokens/color), [chakra ui](https://v2.chakra-ui.com/docs/styled-system/theme#typography)를 참고해서 디자인 토큰을 추가했습니다.
- commomThemeContract를 삭제했습니다.
> [FEAT] 디자인 토큰 추가

- backend/src/main/java/kernel360/techpick/feature/domain/folder/service/FolderServiceImpl.java
- backend/src/main/java/kernel360/techpick/feature/domain/tag/service/TagServiceImpl.java
- Close #322
- 기능 : tag, folder 검증로직 메소드 분리
- issue : #322
- validateTagAccess
- validateDuplicateTagName
- validateFolderAccess
> [REFACTOR] tag, folder 검증로직 메소드 분리

- .github/workflows/multi-module_cicd.yml
> [TEST] 멀티모듈 ci/cd 테스트

- frontend/techpick-shared/themes/commonTheme.css.ts
- Close #353 
- 기능 :
명확히 알 수 없는 부분에 jsdoc을 추가해서 이전보다 쉽게 테마를 사용할 수 있게 변경했습니다.
- issue : #353
> [FEAT] 공통 테마에 jsdoc 추가

- frontend/techpick-shared/themes/commonTheme.css.ts
- frontend/techpick/src/components/FolderTree/CreateFolderInput.tsx
- frontend/techpick/src/components/FolderTree/FolderDraggable.tsx
- frontend/techpick/src/components/FolderTree/FolderInfoItem.tsx
- frontend/techpick/src/components/FolderTree/FolderTreeHeader.tsx
- frontend/techpick/src/components/FolderTree/ShowCreateFolderInputButton.tsx
- frontend/techpick/src/components/FolderTree/TreeNode.tsx
- frontend/techpick/src/components/FolderTree/createFolderInput.css.ts
- frontend/techpick/src/components/FolderTree/folderInfoItem.css.ts
- frontend/techpick/src/components/FolderTree/folderTreeHeader.css.ts
- frontend/techpick/src/components/FolderTree/index.tsx
- frontend/techpick/src/components/FolderTree/showCreateFolderInputButton.css.ts
- frontend/techpick/src/components/FolderTree/tree.css.ts
- frontend/techpick/src/components/FolderTree/treeNode.css.ts
- frontend/techpick/src/components/Text/Text.css.ts
- frontend/techpick/src/constants/index.ts
- frontend/techpick/src/stores/createFolderInputStore.ts
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- frontend/techpick/src/stores/dndTreeStore/treeMockDate.ts
- frontend/techpick/src/utils/index.ts
- frontend/techpick/src/utils/string.ts
- Close #361 
- 기능 :
- issue : #361 
생성에 대한 UI를 적용했고, 중앙 로직을 적용했습니다.
API연결은 아직 안되었으며 폴더에 대한 CRUD를 내부적으로 구현하고 나서 연결할 예정입니다.
https://github.com/user-attachments/assets/b4b3515d-e776-4084-b5e0-e5507751b9a7
> [FEAT] 폴더 생성 UI 및 상태 관리 로직 변경

- frontend/techpick/src/components/FolderTree/FolderContextMenu.tsx
- frontend/techpick/src/components/FolderTree/FolderInfoItem.tsx
- frontend/techpick/src/components/FolderTree/FolderInput.tsx
- frontend/techpick/src/components/FolderTree/TreeNode.tsx
- frontend/techpick/src/components/FolderTree/folderContextMenu.css.ts
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- Close #368 
- 기능 :
- issue : #368
> [FEAT] 폴더 삭제 UI 및 인터렉션 추가

- frontend/Dockerfile
- frontend/techpick/next.config.js
- Close #374 
공식문서의 [Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)을 따라서 다시 Dockerfile을 작성했습니다.
- issue : #374
> [CI/CD] nextjs docker image 사이즈 감소

- backend/docker-compose.yaml
- backend/techpick-core/src/main/resources/application-core.yaml
- Close #388
- 기능 : Local MySQL 접속 설정 변경
- issue : #388
Local MySQL 접속 설정 변경
> [REFACTOR] Local MySQL 접속 설정 변경

- frontend/techpick/package.json
- frontend/techpick/src/app/(signed)/folders/unclassified/page.tsx
- frontend/techpick/src/components/PickListViewerPanel/PickListViewerPanel.css.tsx
- frontend/techpick/src/components/PickListViewerPanel/PickListViewerPanel.tsx
- frontend/techpick/src/components/PickListViewerPanel/SearchWidget/SearchWidget.tsx
- frontend/techpick/src/components/PickListViewerPanel/SearchWidget/tokenInput.css
- frontend/techpick/src/components/PickListViewerPanel/api/getPickList.ts
- frontend/techpick/src/components/PickListViewerPanel/util/tokenizer/PrefixTokenizer.type.ts
- frontend/techpick/src/components/PickListViewerPanel/util/tokenizer/PrefixTokenizerImpl.ts
- frontend/yarn.lock
- Close #411 
- 기능 : 검색 패널 자동 완성
- issue : #411 
- `folder:` --> 폴더 자동 완성
- `#` --> 픽 자동 완성
> [FEAT] 검색창 자동 완성

- frontend/techpick-shared/themes/lightTheme.css.ts
- frontend/techpick/src/components/FolderTree/FolderTreeHeader.tsx
- frontend/techpick/src/components/FolderTree/folderLinkItem.css.ts
- frontend/techpick/src/components/FolderTree/folderTreeHeader.css.ts
- frontend/techpick/src/components/FolderTree/tree.css.ts
- frontend/techpick/src/styles/reset.css.ts
- Close #428 
- 기능 :
- issue : #428
> [DESIGN] 폴더 영역 디자인 개선

- .github/workflows/test-client-deploy.yml
- frontend/techpick/.env.example
- frontend/techpick/src/app/(unsigned)/login/page.tsx
- Close #448 
- 기능 :
- dev와 prod모드에서 각각 다른 redirect url을 적용할 수 있습니다.
- issue : #448
> [FEAT] 로그인 리다이렉트 URL 추가

- frontend/techpick/src/app/(signed)/folders/layout.css.ts
- frontend/techpick/src/app/(signed)/folders/layout.tsx
- frontend/techpick/src/components/Breadcrumb/Breadcrumb.css.ts
- frontend/techpick/src/components/Breadcrumb/Breadcumb.tsx
- frontend/techpick/src/components/Button/Button.css.ts
- frontend/techpick/src/components/FolderPathIndicator/CurrentPathIndicator.css.ts
- frontend/techpick/src/components/FolderPathIndicator/CurrentPathIndicator.tsx
- frontend/techpick/src/components/PickListViewer/PickListViewerInfiniteScroll.tsx
- frontend/techpick/src/components/PickListViewer/pickRecord.css.ts
- frontend/techpick/src/components/PickListViewer/pickRecordListLayout.css.ts
- frontend/techpick/src/components/SearchWidget/SearchInput.css
- frontend/techpick/src/components/SearchWidget/SearchWidget.css.ts
- frontend/techpick/src/components/SearchWidget/SearchWidget.tsx
- frontend/techpick/src/components/SelectedTagItem/SelectedTagContent.css.ts
- frontend/techpick/src/constants/route.ts
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- Close #438 
- 기능 : 검색바에 경로 힌트 추가 및 일부 자동완성 버그 수정
- issue : #438
> [DESIGN] 검색 바 디자인 개선

- backend/techpick-api/src/main/java/techpick/api/domain/folder/exception/ApiFolderErrorCode.java
- Close #467
- 기능 : ApiFolderErrorCode 오타 수정
- issue : #467
일부 에러코드에서
`F0`으로 시작하는것을 `FO`로 수정
> [REFACTOR] ApiFolderErrorCode 오타 수정

- backend/techpick-api/src/main/java/techpick/api/application/folder/dto/FolderApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/folder/dto/FolderResult.java
- Close #484
- 기능 : 폴더 응답에 생성 수정 일시 추가
- issue : #484
폴더 응답에 생성 수정 일시 추가
> [FEAT] 폴더 응답에 생성 수정 일시 추가

- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/PickRepository.java
- Close #512
- 기능 : 픽 수정 시 조회 부분에 비관적 락 추가
- issue : #512
- 개발 서버에서 테스트를 위한 PR입니다.
- 픽 수정 할 때 조회 부분에 비관적 락 추가 및 타임아웃 3초 설정
> [REFACTOR] 픽 수정 시 조회 부분에 비관적 락 추가

- backend/techpick-api/src/main/resources/application.yaml
- Close #526
- 기능 : 운영 서버에서 스웨거 접근 못하도록 변경
- issue : #526
- 운영 서버에서 스웨거 접근 못하도록 변경
- 해당 PR merge 후 release로 PR 요청 날리겠습니다.
> [REFACTOR] 운영 서버에서 스웨거 접근 못하도록 변경

- frontend/techpick/src/apis/tag/createTag.ts
- frontend/techpick/src/apis/tag/deleteTag.ts
- frontend/techpick/src/apis/tag/getTagList.ts
- frontend/techpick/src/apis/tag/updateTag.ts
- frontend/techpick/src/stores/tagStore.ts
- frontend/techpick/src/types/tag.type.ts
- Close #534 
- 기능 :
- issue : #534 
- 과거 변경되지 않은 코드를 변경했습니다.
> [FIX] 웹에서 tag CRUD 변경

- frontend/techpick/src/app/(signed)/folders/layout.tsx
- frontend/techpick/src/components/FolderTree/index.tsx
- Close #575 
- 기능 :
- issue : #575 
- 현재 완전히 구현되지 않아 버그가 발생하거나 예상하지 못한 동작을 수행하는 기능(웹 내에서 픽 생성 및 검색)의 UI를 제거합니다.
> [FIX] 현재 완전히 구현되지 않은 기능 UI 제거

- backend/techpick-api/src/main/java/techpick/api/application/sharedFolder/controller/SharedFolderApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/sharedFolder/dto/SharedFolderApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/sharedFolder/dto/SharedFolderApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/FolderNode.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/PickNode.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderCommand.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/TagNode.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/exception/ApiSharedFolderErrorCode.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/exception/ApiSharedFolderException.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/service/SharedFolderService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/sharedFolder/SharedFolderDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/tag/TagDataHandler.java
- backend/techpick-api/src/main/java/techpick/security/config/SecurityConfig.java
- backend/techpick-api/src/main/java/techpick/security/filter/RequestLoggingFilter.java
- backend/techpick-core/src/main/java/techpick/core/exception/level/NormalErrorLevel.java
- backend/techpick-core/src/main/java/techpick/core/model/sharedFolder/SharedFolder.java
- backend/techpick-core/src/main/java/techpick/core/model/sharedFolder/SharedFolderRepository.java
- backend/techpick-core/src/main/java/techpick/core/util/CachedHttpServletRequest.java
- Close #523
- 기능 : 공유 폴더 기능 구현
- issue : #523
- 공유 시점의 폴더 상태를 snapshot 형태로 저장하고 UUID를 부여
- UUID를 가진 모든 사람(인증 필요x)은 해당 snapshot에 접근 가능
- snapshot은 JSON으로 제공됨
- [`POST`] `/api/shared` : 공유 폴더를 생성합니다.
- [`GET`] `/api/shared/{uuid}` : 공유된 폴더를 조회합니다.
- [`GET`] `/api/shared` : 본인이 공유한 폴더 목록을 조회합니다.
- [`DELETE`] `/api/shared` : 본인이 공유한 폴더를 삭제합니다.
```
{
"uuid": "a0cb5a89-736a-4b5f-90e5-499a805ed28f",
"jsonData": "{\"folderId\":null,\"name\":\"이건공유폴더에요\",\"folders\":[{\"folderId\":12,\"name\":\"Test\",\"folders\":[],\"picks\":[{\"pickId\":105,\"title\":\"(48) 테코톡 - YouTube\",\"url\":\"https://www.youtube.com/results?search_query=%ED%85%8C%EC%BD%94%ED%86%A1\",\"imageUrl\":\"\",\"parentFolderId\":12,\"tags\":[],\"createdAt\":\"2024-11-24T21:34:14.659392\"},{\"pickId\":104,\"title\":\"[Spring Data …
```
> [FEAT] 공유 폴더 기능 구현

- backend/build.gradle
- backend/settings.gradle
- backend/techpick-collector/Dockerfile
- backend/techpick-collector/src/main/java/techpick/TechPickCollectorApplication.java
- backend/techpick-collector/src/main/resources/application.yaml
- backend/techpick-collector/src/main/resources/logback-spring.xml
- Close #596
- 기능 : 수집기 모듈 구성
- issue : #596
수집기 모듈 구성
> [FEAT] 수집기 모듈 구성

- backend/build.gradle
- backend/settings.gradle
- backend/techpick-collector/Dockerfile
- backend/techpick-collector/build.gradle
- backend/techpick-collector/src/main/java/techpick/TechPickCollectorApplication.java
- backend/techpick-collector/src/main/resources/application.yaml
- backend/techpick-collector/src/main/resources/logback-spring.xml
- Close #596
- 기능 : 누락된 gradle 추가
- issue : #596
> [REFACTOR] 수집기 모듈에 누락된 gradle 추가

- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- Close #604
- 기능 : 루트 폴더에 픽 생성하지 못하도록 수정
- issue : #604
- 루트 폴더에 픽 생성하지 못하도록 수정
> [REFACTOR] 루트 폴더에 픽 생성하지 못하도록 수정

- frontend/techpick/src/hooks/useGetDragOverStyle.ts
- Close #616 
- 기능 :
- issue : #
https://github.com/user-attachments/assets/9f6edac1-bdc2-4861-96b4-fd399c0b848b
> [FIX] drag 끝날 때마다 MousePosition 초기화

- frontend/techpick/src/components/FolderTree/FolderContextMenu.tsx
- frontend/techpick/src/components/FolderTree/FolderListItem.tsx
- frontend/techpick/src/components/FolderTree/MoveFolderToRecycleBinDialog.tsx
- frontend/techpick/src/components/FolderTree/moveFolderToRecycleBinDialog.css.ts
- Close #618 
- 기능 :
곧바로 삭제되는 이전과 달리 이제는 한번 더 확인한 뒤에 삭제를 진행합니다.
- issue : #618
> [FEAT] 휴지통 삭제 다이얼로그 추가

- backend/techpick-api/src/main/java/techpick/api/config/SwaggerConfig.java
- Close #626
- 기능 : Swagger에 로그인/로그아웃 명세 추가
- issue : #626
Swagger에 로그인/로그아웃 명세 추가
> [REFACTOR] Swagger에 로그인/로그아웃 명세 추가

- backend/build.gradle
- backend/docker-compose.yaml
- backend/techpick-collector/src/main/java/techpick/TechPickCollectorApplication.java
- backend/techpick-collector/src/main/java/techpick/collector/application/ProducerController.java
- backend/techpick-collector/src/main/java/techpick/collector/config/RabbitmqConfig.java
- backend/techpick-collector/src/main/java/techpick/collector/domain/ProducerService.java
- backend/techpick-collector/src/main/java/techpick/collector/domain/messageComponent.java
- backend/techpick-collector/src/main/java/techpick/collector/dto/MessageDto.java
- backend/techpick-collector/src/main/java/techpick/collector/entity/Message.java
- backend/techpick-collector/src/main/java/techpick/collector/entity/PickPick.java
- backend/techpick-collector/src/main/java/techpick/collector/repository/MessageRepository.java
- backend/techpick-collector/src/main/java/techpick/collector/repository/PickPickRepository.java
- backend/techpick-collector/src/main/java/techpick/collector/test/EmitLog.java
- backend/techpick-collector/src/main/java/techpick/collector/test/NewTask.java
- backend/techpick-collector/src/main/java/techpick/collector/test/ReceiveLogs.java
- backend/techpick-collector/src/main/java/techpick/collector/test/Recv.java
- backend/techpick-collector/src/main/java/techpick/collector/test/Send.java
- backend/techpick-collector/src/main/java/techpick/collector/test/Worker.java
- backend/techpick-collector/src/main/resources/application.yaml
- Close #598
- 기능 : RabbitMQ, MongoDB 설정  
- issue : #598
- RabbitMQ 설정 합치기 위한 PR
> [FEAT] RabbitMQ, MongoDB 설정  

- frontend/schema/schema.d.ts
- frontend/techpick/src/components/FolderTree/FolderListItem.tsx
- frontend/techpick/src/stores/dndTreeStore/dndTreeStore.ts
- frontend/techpick/src/types/sharedFolder.type.ts
- Close #639 
- 기능 :
- issue : #
> [FIX] 폴더 공유 API 타입 변경에 따른 타입 변경

- backend/techpick-api/src/main/java/techpick/api/application/sharedFolder/dto/SharedFolderApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/dto/SharedFolderResult.java
- Close #668 
- 기능 : 스웨거 DTO 용 반환 타입 @NotNull @NotEmpty 추가
- issue : #668
> [FIX] 프론트엔드용 스웨거 수정

- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/Pick.java
- backend/techpick-core/src/main/java/techpick/core/model/pick/PickTag.java
- Close #671
- 기능 : PickTag 낙관적 락 제거 및 unique index 설정
- issue : #671
- PickTag 낙관적 락 제거 및 unique index 설정
- 추후 분산 락으로 변경 예정
> [REFACTOR] PickTag 낙관적 락 제거 및 unique index 설정

- backend/techpick-core/src/main/java/techpick/core/config/P6SpySqlLoggerConfig.java
- backend/techpick-core/src/main/resources/application-core.yaml
- backend/techpick-core/src/main/resources/spy.properties
- backend/techpick-ranking/src/main/resources/logback-spring.xml
- Close #614
- 기능 : p6spy 로그 설정 수정
- issue : #614
`application-core.yaml`에 명시적으로 운영서버에서 로깅 안되게 설정
```
2024-12-05 19:04:04.363  INFO 37014 --- [nio-8080-exec-3] p6spy                                    : 
select
u1_0.id,
u1_0.created_at,
u1_0.deleted_at,
u1_0.email,
u1_0.nickname,
u1_0.password,
u1_0.role,
u1_0.social_provider,
u1_0.social_provider_id,
u1_0.tag_order,
u1_0.updated_at 
from
user u1_0 
where
u1_0.id=1 
and (
u1_0.deleted_at IS NULL
)
2024-12-05 19:04:04.401  INFO 37014 --- [nio-8080-exec-3] p6spy                                    : 
insert 
into
folder
(child_folder_order, pick_order, created_at, folder_type, name, parent_folder_id, updated_at, user_id) 
values
('', '', '2024-12-05T19:04:04.378+0900', 'GENERAL', 'backend', 1, '2024-12-05T19:04:04.378+0900', 1)
2024-12-05 …
```
> [REFACTOR] p6spy 로그 설정 수정

- backend/techpick-api/src/main/java/techpick/security/filter/RequestLoggingFilter.java
- backend/techpick-api/src/main/resources/logback-spring.xml
- Close #685
- 기능 : 로깅시 요청마다 UUID 부여
- issue : #685
MDN에 요청 마다 UUID 저장
`[%X{requestId}][%d{yyyy-MM-dd HH:mm:ss}:%-3relative] %-5level %logger{35} - %msg%n`
requestId = 요청별 UUID
> [FEAT] 로깅시 요청마다 UUID 부여

- backend/techpick-api/src/main/java/techpick/api/config/SwaggerConfig.java
- Close #690
- 기능 :  Swagger Security Scheme 추가
- issue : #690
스웨거 테스트를 위한 Swagger Security Scheme 추가
> [REFACTOR]  Swagger Security Scheme 추가

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/controller/RankingApiController.java
- backend/techpick-api/src/main/java/techpick/api/domain/link/service/LinkService.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickDataHandler.java
- backend/techpick-api/src/main/java/techpick/api/lib/opengraph/Metadata.java
- backend/techpick-api/src/main/java/techpick/api/lib/opengraph/OpenGraph.java
- backend/techpick-api/src/main/java/techpick/api/lib/opengraph/OpenGraphException.java
- backend/techpick-api/src/main/java/techpick/api/lib/opengraph/OpenGraphOption.java
- backend/techpick-api/src/main/java/techpick/api/lib/opengraph/OpenGraphReader.java
- Close #697 
- 기능 : 
1. 프론트엔드에서 요청했던 Pick 존재 여부 확인 API 추가 (Boolean 값으로 확인할 수 있게)
2. 기존 OpenGraph 파싱 방식을 별도 클래스로 리팩토링 
- issue : #697
> [REFACTOR] Pick 존재 여부 확인 API + OpenGraph 획득 방식 리팩토링

- backend/techpick-api/src/main/java/techpick/api/application/event/controller/EventApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/event/dto/EventApiRequest.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/pick/dto/PickApiResponse.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/controller/RankingApiController.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/LinkInfoWithCount.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/RankingApiMapper.java
- backend/techpick-api/src/main/java/techpick/api/application/ranking/dto/RankingResponse.java
- backend/techpick-api/src/main/java/techpick/api/domain/link/dto/LinkMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickMapper.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/dto/PickResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickService.java
- backend/techpick-api/src/main/java/techpick/api/domain/ranking/dto/RankingResult.java
- backend/techpick-api/src/main/java/techpick/api/domain/ranking/service/RankingService.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/link/LinkDataHandler.java
- Close #697 
- 기능 : 픽 조회시, 랭킹에 포함되어 있을 경우 조회수도 함께 표시
- issue : #697
> [FEAT] 랭킹 정보를 픽 리스트에서 함께 표시

- backend/techpick-api/src/main/java/techpick/api/application/pick/controller/PickApiController.java
- backend/techpick-api/src/main/java/techpick/api/domain/pick/service/PickSearchService.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/InitialFolderStrategy.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/UserService.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/ContentInitStrategy.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/InitStrategyConfiguration.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/ManualInitStrategy.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/RankingInitStrategy.java
- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/StarterFolderStrategy.java
- backend/techpick-api/src/main/java/techpick/api/infrastructure/pick/PickQuery.java
- Close #717 
- 기능 : 회원 가입시 메뉴얼도 기본 폴더에 추가
- issue : #717
> feat: 회원 가입시 최초 북마크 생성 로직

- backend/techpick-api/src/main/java/techpick/api/application/tag/controller/TagApiController.java
- backend/techpick-api/src/main/java/techpick/api/domain/tag/exception/ApiTagErrorCode.java
- backend/techpick-api/src/main/java/techpick/api/domain/tag/exception/ApiTagException.java
- Close #704
- 기능 : 태그 최대 길이 200자로 제한
- issue : #704
- 태그 최대 길이 200자로 제한
- 태그 에러 코드, 예외 추가
> [BUG] 태그 최대 길이 제한

- frontend/techpick/src/hooks/useMyShareFolder.ts
- Close #703
- 기능 :공유 폴더 취소를 빠르게 연속으로 누를 때 발생했던 동시성 문제 해결
- issue : #703
> [FIX] 공유 폴더 취소 시 동시성 문제 해결

- backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/util/LoginUserIdDistributedLockAspect.java
- backend/techpick-api/src/test/java/techpick/api/domain/pick/service/PickServiceTest.java
- Close #711
- 기능 : 락 설정 실패 시 예외 발생
- issue : #711
> [REFACTOR] 락 설정 실패 시 예외 발생

- backend/techpick-api/src/main/java/techpick/api/domain/user/service/strategy/RankingInitStrategy.java
- Close #730
- 기능 : 회원가입시 링크가 존재하지 않을 경우 링크를 생성하는 로직 추가
- issue : #730
회원가입시 상위랭킹 링크들을 추가할 때, mysql에 해당 링크가 저장되어 있지 않으면 예외 발생
회원가입시 상위랭킹 링크들을 추가할 때, mysql에 해당 링크가 저장되어 있지 않으면 링크 생성 후 회원가입 진행
회원가입 시간 단축을 위해 상위랭킹 링크 조회 값을 5로 변경
-> `private static final Integer LOAD_LIMIT = 5;`
> [FIX] 회원가입이 완료되지 않는 버그 수정

- backend/techpick-api/src/main/java/techpick/api/domain/ranking/service/RankingService.java
- Close #732
- 기능 : 지난 한달간 픽 많이한 기준을 어제가 아닌 오늘로 변경
- issue : #732
지난 한달간 픽 많이한 기준을 어제가 아닌 오늘로 변경
> [REFACTOR] 지난 한달간 픽 많이한 기준을 어제가 아닌 오늘로 변경

- backend/techpick-api/src/main/java/techpick/api/config/HttpApiConfiguration.java
- Close #735
- 기능 : RestClient 타임아웃 설정
- issue : #735
- 타임아웃 설정 시간을 현재 500ms로 하였는데 적절한 시간이 있을까요?
> [REFACTOR] RestClient 타임아웃 설정

- frontend/techpick/sentry.client.config.ts
- frontend/techpick/sentry.edge.config.ts
- frontend/techpick/sentry.server.config.ts
- Close #740 
- 기능 : 클라이언트에서 에러가 발생하면 센트리에서 에러 발생 1분 전부터의 행동 로그를 영상처럼 보여줍니다.
- issue : #740
> [FEAT] add session replay

- backend/techpick-api/src/main/java/techpick/api/domain/sharedFolder/service/SharedFolderService.java
- Close #747
- 기능 : new ArrayList<>(size) 로 크기를 잡았을 뿐 실제 메모리 할당을 하지 않아 발생 
- issue : #747
> [bug] 태그 배열 할당 버그

- frontend/techpick/src/components/FolderTree/folderLinkItem.css.ts
- frontend/techpick/src/components/FolderTree/folderTreeHeader.css.ts
- frontend/techpick/src/components/FolderTree/tree.css.ts
- Close #694 
- 기능 : 사이드바의 색상을 변경했습니다
- issue : #694
> style: 사이드바 색상 변경

- frontend/techpick/src/app/(signed)/layout.tsx
- frontend/techpick/src/components/FolderTree/UserMenuBar.tsx
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- frontend/techpick/src/components/ShortcutKey.tsx
- frontend/techpick/src/utils/eventEmitter.ts
- Close #772
- 기능 : cmd + p를 누르면 검색 다이얼로그가 열리고 / 닫힙니다.
- issue : #772
> [FEAT] 검색 다이얼로그 단축키 이벤트 핸들러, 컴포넌트 추가

- frontend/techpick/src/components/Search2/customSelectStyles.ts
- Close #784
- 기능 : input창의 길이를 제한했습니다.
- issue : #784
> [FIX]: search filter select input 길이 제한

- frontend/techpick-extension/src/components/CreatePickForm.css.ts
- frontend/techpick-extension/src/components/TagAutocompleteDialog.css.ts
- frontend/techpick-extension/src/components/TagAutocompleteDialog.tsx
- frontend/techpick-extension/src/components/TagInfoEditPopoverButton.tsx
- frontend/techpick-extension/src/components/TagPicker.tsx
- frontend/techpick-extension/src/libs/@chrome/unescapeHTML.ts
- frontend/techpick-extension/src/libs/@chrome/useGetTabInfo.tsx
기능 : 
issue : 
- #806 
- #808 
- #805 
- #803 
- 익스텐션 제출 전에 QA를 하며 발견된 버그를 수정했습니다.
- 또한 `TagDialog`가 켜져있어도 버튼을 바로 누를 수 있게 동작하
> [FIX] 익스텐션 제출 전 최종 수정

- frontend/techpick-extension/src/chrome-extension/manifest.json
- frontend/techpick-extension/src/components/CreatePickForm.css.ts
- frontend/techpick-extension/src/components/TagAutocompleteDialog.css.ts
- frontend/techpick-extension/src/components/TagAutocompleteDialog.tsx
- frontend/techpick-extension/src/components/TagInfoEditPopoverButton.tsx
- frontend/techpick-extension/src/components/TagPicker.tsx
- frontend/techpick-extension/src/libs/@chrome/unescapeHTML.ts
- frontend/techpick-extension/src/libs/@chrome/useGetTabInfo.tsx
- 기능 :
- issue : #
- version이 0.2 에서 0.3으로 올라갔습니다.
> [CHORE] 익스텐션 버전 업그레이드 명시

- frontend/techpick/src/components/FolderTree/SarchBarDescription.tsx
- frontend/techpick/src/components/FolderTree/SearchBar.tsx
- frontend/techpick/src/components/FolderTree/searchBar.css.ts
- frontend/techpick/src/components/Search2/FilterContainer.tsx
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- frontend/techpick/src/components/Search2/searchDialog.css.ts
- frontend/techpick/src/components/ShortcutKey.tsx
- frontend/techpick/src/constants/index.ts
- frontend/techpick/src/constants/openSearchDialogEvent.ts
- frontend/techpick/src/utils/index.ts
- frontend/techpick/src/utils/isMacOS.ts
- 기능 :
윈도우에서도 단축키를 입력해도 가능하게 로직을 수정했습니다.
- issue : #815 
- 검색바의 디자인이 변경되었습니다.
- 필터가 바로 보이게 수정되었습니다.
> [FEAT] 필터 토글 삭제, 검색 바 디자인 변경

- frontend/techpick/src/app/layout.tsx
- frontend/techpick/src/components/FeedbackToolbar.tsx
- frontend/techpick/src/components/FolderTree/MyPagLinkItem.tsx
- frontend/techpick/src/components/FolderTree/index.tsx
- frontend/techpick/src/components/FolderTree/myPagLinkItem.css.ts
- frontend/techpick/src/components/FolderTree/tree.css.ts
- frontend/techpick/src/components/ShortcutKey.tsx
- frontend/techpick/src/components/feedbackToolbar.css.ts
- frontend/techpick/src/hooks/useFolderToFolderDndMonitor.tsx
- Close #824 
- 기능 :
- issue : #824 
- tooltip 위치 변경했습니다.
- 폴더 드래그 종료시 해당 드래그 목록으로 이동하는 로직을 추가 했습니다.
> [FEAT] front

- backend/baguni-api/src/main/java/baguni/api/domain/ranking/service/RankingService.java
- Close #839
- 기능 : 오늘 핫한 북마크 기준 날짜 변경
- issue : #839
- 기존에 기준 날짜가 어제~오늘 데이터를 보여주었습니다.
- 오늘 데이터만 보여주도록 변경하였습니다.
> [REFACTOR] 오늘 핫한 북마크 기준 날짜 변경

- frontend/techpick/src/components/DragOverlay/DragOverlay.tsx
- frontend/techpick/src/components/DragOverlay/PickRecordOverlay.tsx
- frontend/techpick/src/components/DragOverlay/folderItemOverlay.css.ts
- frontend/techpick/src/components/DragOverlay/pickRecordOverlay.css.ts
- Close #862 
- 기능 :
- issue : #862 
- css design만 수정되었습니다.
> [DESIGN] 드래그 앤 드랍 오버레이 투명도 반영

- .github/workflows/baguni.test.client.deploy.yml
- .github/workflows/playwright.test.yml
- frontend/techpick/next.config.js
- frontend/techpick/sentry.client.config.ts
- frontend/techpick/sentry.edge.config.ts
- frontend/techpick/sentry.server.config.ts
- 기능 :
- issue : #859 
- sentry 계정을 변경했습니다.
- branch 변경에 따른 action의 branch 명도 변경했습니다.
- local에서 에러가 나는건 추적이 되는지 확인했습니다. vercel과 연동도 되었기에 개발서버와 배포 서버에서도 문제가 있는지 확인해야합니다.
> [CI/CD] sentry 계정 변경

- backend/baguni-common/src/main/java/baguni/common/event/RabbitMqEventMessenger.java
- backend/baguni-ranking/src/main/java/baguni/ranking/infra/RabbitMqEventListener.java
> [HOT-FIX] 메시지 수신 로그 추가

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiRequest.java
- backend/baguni-api/src/main/java/baguni/api/infrastructure/pick/PickDataHandler.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/dto/PickCommand.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- Close #907
- 기능 : 픽 수정 API v2 제거
- issue : #907
- 기획 변경으로 인해 v2 제거
- 기존 기획인 픽 수정 시 폴더 이동도 가능하도록 변경
> [REFACTOR] 픽 수정 API v2 제거

- backend/baguni-api/src/main/java/baguni/api/application/user/controller/UserApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/user/controller/dto/UserApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/user/controller/dto/UserInfoApiResponse.java
- backend/baguni-api/src/main/java/baguni/api/service/user/dto/UserInfo.java
- backend/baguni-api/src/main/java/baguni/api/service/user/service/UserService.java
- backend/baguni-api/src/main/java/baguni/security/exception/ApiAuthErrorCode.java
- backend/baguni-api/src/main/java/baguni/security/exception/ApiAuthException.java
- backend/baguni-api/src/main/java/baguni/security/handler/BaguniApiAuthExceptionEntrypoint.java
- backend/baguni-api/src/main/java/baguni/security/handler/BaguniLogoutHandler.java
- backend/baguni-api/src/main/java/baguni/security/util/AccessToken.java
- backend/baguni-api/src/main/java/baguni/security/util/CookieUtil.java
- backend/baguni-api/src/main/resources/logback-spring.xml
- backend/baguni-batch/src/main/resources/logback-spring.xml
- backend/baguni-ranking/src/main/resources/logback-spring.xml
- Close #914 
- 기능 : 
1. 프론트에서 쿠키에 접근할 수 없어서 `내 정보 획득` api를 추가했습니다.
2. 백엔드에서 비유효 쿠키를 제거합니다. 모든 `au-001` 코드는 쿠키를 초기화합니다.
- issue : #914
> [FEAT] FE 사용자 식별자 획득 API 추가

- frontend/techpick/src/app/(signed)/folders/unclassified/page.tsx
- frontend/techpick/src/components/PickRecord/PickRecordHeader.tsx
- frontend/techpick/src/components/PickRecord/pickRecordHeader.css.ts
- frontend/techpick/src/components/pickContentLayout.css.ts
- 기능 : 헤더의 높이를 조금 높이고 한국어로 변경했습니다.
- issue : #
| <img width="1095" alt="스크린샷 2025-01-08 오후 5 57 55" src="https://github.com/user-attachments/assets/8c7b121f-af3d-4bdf-9ecf-10d2b601a39d" />| <img width="1136" alt="스크린샷 2025-01-08 오후 5 57 35" src="https://github.com/user-attachments/assets/dc2821a7-7519-4c77-b8d3-73d9e335d825" />) |
> [DESIGN] 픽 헤더 제목 영어 대신 한국어로 변경

- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/dto/PickApiRequest.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- Close #927 
- 기능 : 혼동 방지를 위해 익스텐션과 웹에서의 픽 수정 API를 분리합니다.
- issue : #927
> [FIX] 서비스 / 익스텐션 픽 수정 API 분리

- backend/baguni-api/src/main/java/baguni/api/service/chromebookmark/service/ChromeBookmarkService.java
- backend/baguni-api/src/main/java/baguni/api/service/folder/service/FolderService.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickSearchService.java
- backend/baguni-api/src/main/java/baguni/api/service/sharedFolder/service/SharedFolderService.java
- backend/baguni-api/src/main/java/baguni/api/service/tag/service/TagService.java
- Close #936 
- 기능 : :warning: assert 냐 validate 이냐가 중요한게 아니고, 메서드 명을 구체적으로 변경하는데 의미를 둔 PR 입니다. 얘가 무엇을 검증하는지를 메서드 명에 반영했어요.
- issue : #936
> [CHORE] validation 메서드 명을 더 상세하게 변경

- frontend/techpick-extension/src/chrome-extension/manifest.json
- frontend/techpick-extension/src/components/UpdatePickForm.tsx
- frontend/techpick-extension/src/pages/BookmarkPage.tsx
- Close #959 
기능 :
- 이제 북마크가 추가되자마자 알림이 생성됩니다.
- 수정한 뒤에 닫히는 시간이 빨라졌습니다. (0.9초에서 0.6초로 변경)
- issue : #959
- 배포를 위해 익스텐션 버전을 올렸습니다
> [FEAT] 익스텐션 배포 전 개선

- frontend/biome.json
- frontend/techpick/src/app/(signed)/folders/[folderId]/page.tsx
- frontend/techpick/src/app/(signed)/recommend/page.tsx
- frontend/techpick/src/app/(unsigned)/landing/SignUpLink.tsx
- frontend/techpick/src/app/(unsigned)/landing/page.css.ts
- frontend/techpick/src/app/(unsigned)/landing/page.tsx
- frontend/techpick/src/app/(unsigned)/login/failed/page.tsx
- frontend/techpick/src/app/(unsigned)/login/layout.tsx
- frontend/techpick/src/app/(unsigned)/login/page.tsx
- frontend/techpick/src/app/(unsigned)/share/[uuid]/LandingPageLinkButton.tsx
- frontend/techpick/src/app/(unsigned)/share/[uuid]/SignUpLinkButton.tsx
- frontend/techpick/src/app/(unsigned)/share/[uuid]/page.tsx
- frontend/techpick/src/app/api/sentry-example-api/route.ts
- frontend/techpick/src/components/DisableDroppableZone.tsx
- frontend/techpick/src/components/FeaturedSection/FeaturedSection.tsx
- frontend/techpick/src/components/MyPage/MyPageContentContainer.tsx
- frontend/techpick/src/components/ScreenLogger.tsx
- frontend/techpick/src/components/Search2/FilterContainer.tsx
- frontend/techpick/src/components/Search2/HoverCard.tsx
- frontend/techpick/src/components/Search2/SearchDialog.tsx
- frontend/techpick/src/components/Search2/SearchInfiniteScrollList.tsx
- frontend/techpick/src/components/Search2/SearchItemRenderer.tsx
- frontend/techpick/src/components/ToggleThemeButton.tsx
- frontend/techpick/src/components/TutorialDialog.tsx
- frontend/techpick/src/hooks/useEventLogger.ts
- frontend/techpick/src/styles/dialogStyle.css.ts
- #982 
해당 버그의 원인은 `Collision detection algorithms`이 가장 가까운 dropzone으로 이동하는 것이 원인이었습니다. 
즉, 어디에든 드랍하면 가장 가까운 드롭존의 이벤트가 발생하는 것이 원인이여서 폴더로 이동하지 않아도 폴더에 새로운 북마크가 생성되었습니다. 특정 영역에 드랍을 하더라도 이벤트를 발생하지 않는 컴포넌트를 구현하여서 해결하였습니다.
- #983 
해당 버그의 원인은 onClick이 제대로 실행이 되지 않는 것이었습니다. 인자로 event가 들어가서 발생하는 버그인 것으로 추측됩니다.
- 랜딩 페이지 방문 여부
- 로그인 페이지 방문 여부
- 공유 폴더 페이지 -> 랜딩 페이지 이동 여부
화면이 렌더링이 된 후에 애니메이션이 동작하는데 순간 화면이 보였다가 다시 애니메이션이 적용되 슬그머니 등장했습니다. 따라서 처음부터 화면이 보이지 않고 애니메이션이 동작하면 화면이 보이게 변경했습니다.
> [FIX] 이벤트 수집 정상화, 드래그앤 드랍 버그 수정, 

- backend/baguni-api/build.gradle
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/controller/BlogArticleApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/controller/RankingApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/dto/LinkInfoWithCount.java
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/dto/RankingApiMapper.java
- backend/baguni-api/src/main/java/baguni/api/application/suggestion/dto/RankingResponse.java
- backend/baguni-api/src/main/java/baguni/api/service/link/service/LinkService.java
- backend/baguni-common/build.gradle
- backend/baguni-common/src/main/java/baguni/common/config/CacheConfig.java
- backend/baguni-common/src/main/java/baguni/common/lib/cache/CacheType.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkRepository.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/dto/LinkMapper.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/dto/RssLinkInfo.java
- backend/baguni-ranking/src/main/java/baguni/ranking/domain/pick/PickRankingService.java
- Close #974 
- 기능 : 최근 유명 블로그 글 15개 제공 API 구현
- issue : #974
> [FEAT] 유명 블로그 글 소개 API 

- backend/baguni-domain/src/main/java/baguni/domain/lock/MysqlLockProvider.java
- Close #1013
- 기능 : 락 해제 실패 시 DB 세션 로그 추가
- issue : #1012
#1012 이슈 확인 부탁드립니다.
> [REFACTOR] 락 해제 실패 시 DB 세션 로그 추가

- backend/baguni-api/src/main/java/baguni/api/config/HttpApiConfiguration.java
- backend/baguni-api/src/main/resources/logback-spring.xml
- backend/baguni-batch/src/main/java/baguni/batch/config/RestClientConfig.java
- backend/baguni-batch/src/main/java/baguni/batch/domain/rss/service/RssFeedService.java
- backend/baguni-batch/src/main/resources/logback-spring.xml
- backend/baguni-common/build.gradle
- backend/baguni-common/src/main/java/baguni/common/config/RabbitmqConfig.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/ErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/FatalErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/NormalErrorLevel.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/WarningErrorLevel.java
- backend/baguni-common/src/main/resources/application-common.yaml
- backend/baguni-domain/src/main/resources/application-domain.yaml
- backend/baguni-ranking/src/main/resources/logback-spring.xml
- backend/build.gradle
- Close #966 
- 기능 : 기존 Logback 설정에서 파일에 저장할 때 json 포맷으로 저장되도록 변경. 
- issue : #966
> [FIX] Logback 파일 저장 포맷 변경 

- backend/baguni-api/src/main/java/baguni/api/application/extension/controller/ExtensionApiControllerV1.java
- backend/baguni-api/src/main/java/baguni/api/application/folder/controller/FolderApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/link/controller/LinkApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/sharedFolder/controller/SharedFolderApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/tag/controller/TagApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/user/controller/UserApiController.java
- backend/baguni-api/src/main/resources/application.yaml
- Close #1039
- 기능 : 스웨거 정렬
- issue : #1039
- 스웨거 태그에 영어로 작성된 부분과 한글로 작성된 부분이 섞여서 표현되는 문제 -> 알파벳 순으로 정렬
- 태그를 모두 한글로 수정(Pick API -> 픽 API)
- HTTP Method 정렬 기준이 path 순서 -> (DELETE, GET, PATCH, POST, PUT) 순으로 정렬
- 가나다, abc 순으로 정렬됩니다.
- DELETE, GET, PATCH, POST, PUT 순으로 정렬됩니다. 
추후 Swagger version 명시하고 싶으면 아래와 같이 설정
```
springdoc:
swagger-ui:
urls:
- name: v1 API
url: /api-docs/v1
- name: v2 API
url: /api-docs/v2
- name: v3 API
url: /api-docs/v3
```
컨트롤러에서 /api/v1/picks 이런 방식으로 정의하면 그에 맞게 versioning 될 것이라 생각합니다.
> [REFACTOR] 스웨거 정렬 

- backend/baguni-batch/src/main/java/baguni/batch/config/RestClientConfig.java
- backend/baguni-batch/src/test/java/baguni/batch/domain/rss/service/RssFeedServiceTest.java
- backend/baguni-batch/src/test/resources/application.yaml
- Close #1042
- 기능 : RestClientConfig에 user-agent 추가
- issue : #1042
RestClient에 user-agent가 누락되어 있어 추가하였습니다.
테스트 코드 돌려본 결과, 제대로 가져오는 것을 확인했습니다.
> [FIX] RestClientConfig에 user-agent 추가

- backend/baguni-api/src/main/java/baguni/api/application/mobile/controller/MobileApiController.java
- backend/baguni-api/src/main/java/baguni/api/application/pick/controller/PickApiController.java
- Close #1052
- 기능 : 픽 페이지네이션 API 이동
- issue : #1052
- 픽 페이지네이션 API는 웹, 모바일 둘 다 사용합니다.
- 모바일 전용 API에서 픽 API로 이동시켰습니다.
- GET `/api/picks/pagination`
- #1050
해당 이슈에 문제가 될 사항에 대해 작성해두었습니다.
> [REFACTOR] 픽 페이지네이션 API 이동

- backend/baguni-common/src/main/java/baguni/common/util/MapUtil.java
> [CHORE] main 브랜치로 병합

- frontend/techpick-extension/src/chrome-extension/manifest.json
- frontend/techpick-extension/src/components/CreatePickForm.tsx
- Close #1058 
- #1058 
수정하기에서 생성하기로 변경했습니다
> [FIX] 익스텐션 잘못된 텍스트 수정

- backend/baguni-api/src/main/java/baguni/api/service/folder/service/FolderService.java
- backend/baguni-api/src/main/java/baguni/api/service/link/service/LinkService.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickSearchService.java
- backend/baguni-api/src/main/java/baguni/api/service/pick/service/PickService.java
- backend/baguni-api/src/main/java/baguni/api/service/ranking/service/RankingService.java
- backend/baguni-api/src/main/java/baguni/api/service/sharedFolder/service/SharedFolderService.java
- backend/baguni-api/src/main/java/baguni/api/service/tag/service/TagService.java
- backend/baguni-api/src/main/java/baguni/api/service/user/service/UserService.java
- backend/baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkAnalyzer.java
- backend/baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
- backend/baguni-batch/src/main/java/baguni/batch/domain/rss/service/RssFeedService.java
- backend/baguni-ranking/src/main/java/baguni/ranking/domain/pick/PickRankingService.java
- 기능 :
서비스 코드 변경 사항 없습니다!
이 수정은 모두 OpenTelemetry Trace (Span) 수집과 관련 있습니다.
작업을 개발 서버에서 확인하기 위한 중간 PR 입니다.
`@WithSpan` 어노테이션을 붙여서 잘 기록되는지 확인하고자 합니다.
- issue : #1048
> [CHORE] 각 서비스 메서드에 Trace 추적

- backend/baguni-api/src/main/java/baguni/api/infrastructure/user/UserDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/folder/FolderDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/link/LinkDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/pick/PickDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/sharedFolder/SharedFolderDataHandler.java
- backend/baguni-domain/src/main/java/baguni/domain/infrastructure/tag/TagDataHandler.java
- 기능 :
DataHandler에 Span 생성 추가
- issue : #1048
> [CHORE] 각 DataHandler 메서드에 Trace 추가

- frontend/techpick/src/app/layout.css.ts
- frontend/techpick/src/app/layout.tsx
- issue : #1090 
해당 이슈와 동일한 문제이고 html tag에도 적용했습니다.
> [FIX] 추천 페이지에서 pull to refresh가 2개가 생기는 문제 수정

- frontend/techpick/src/app/(signed)/layout.css.ts
- frontend/techpick/src/app/(signed)/mypage/page.css.ts
- frontend/techpick/src/app/(signed)/recommend/page.css.ts
- frontend/techpick/src/app/(unsigned)/login/page.css.ts
- frontend/techpick/src/app/global-error.css.ts
- frontend/techpick/src/app/not-found.css.ts
- frontend/techpick/src/components/MyPage/myPageShareFolderContent.css.ts
- frontend/techpick/src/components/PickTagPicker/TagInfoEditPopoverButton.css.ts
- frontend/techpick/src/components/SideNavigationBar/sideNavigationBar.css.ts
- frontend/techpick/src/components/folderContentLayout.css.ts
- frontend/techpick/src/components/mobileEmptyPickRecordImage.css.ts
- frontend/techpick/src/components/mobilePickInfiniteScrollList.css.ts
- #1086 
사파리에서 스크롤이 생겼었는데 찾아보니 100vh의 영역위로 url이나 하단 탭바가 생겨서 스크롤이 생기는 것이었습니다. dvh로 변경해서 해당 이슈를 해결하려합니다.
> [DESIGN] vh를 dvh로 변경

- README.md
- Close #1075 
- 기능 : Readme 서비스 아키텍쳐 그림 업데이트
- issue : #1075
> [DOCS] 서비스 구성도 업데이트

- backend/baguni-api/src/main/java/baguni/security/filter/TestUserAuthenticationFilter.java
- backend/baguni-common/src/main/java/baguni/common/exception/level/NormalErrorLevel.java
에러 코드 출력을 테스트하기 위한 임시 레벨 설정입니다.
info 레벨을 error로 바꿨습니다.
그라파나 알림 설정 완료되면 다시 되돌리겠습니다.!
> [TEST] 에러 로그 테스트를 위한 레벨 임시 변경 (추후 복구 예정)

- backend/baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
- Close #1122
- 기능 : 링크 업데이트 관련 버그 수정
- issue : #1122
- 링크의 title은 항상 존재할 수 밖에 없음.
- title이 비어있는 경우 링크 업데이트 못하도록 변경
> [REFACTOR] 링크 업데이트 관련 버그 수정

- .github/workflows/baguni.prod.api.deploy.yml
- .github/workflows/baguni.prod.batch.deploy.yml
- .github/workflows/baguni.prod.ranking.deploy.yml
- .github/workflows/baguni.test.api.deploy.yml
- .github/workflows/baguni.test.batch.deploy.yml
- .github/workflows/baguni.test.client.deploy.yml
- .github/workflows/baguni.test.ranking.deploy.yml
> [CHORE] discord webhook 알림 삭제
